// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: plugin/pkg/services/agentpools/nebius/instance/agentpools.proto

package instance

import (
	api "github.com/Azure/aks-flex/plugin/api"
	kubeadm "github.com/Azure/aks-flex/plugin/pkg/services/agentpools/api/features/kubeadm"
	wireguard "github.com/Azure/aks-flex/plugin/pkg/services/agentpools/api/features/wireguard"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentPool struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Metadata *api.Metadata          `protobuf:"bytes,1,opt,name=metadata"`
	xxx_hidden_Spec     *AgentPoolSpec         `protobuf:"bytes,2,opt,name=spec"`
	xxx_hidden_Status   *AgentPoolStatus       `protobuf:"bytes,3,opt,name=status"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AgentPool) Reset() {
	*x = AgentPool{}
	mi := &file_flex_plugin_pkg_services_agentpools_nebius_instance_agentpools_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentPool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentPool) ProtoMessage() {}

func (x *AgentPool) ProtoReflect() protoreflect.Message {
	mi := &file_flex_plugin_pkg_services_agentpools_nebius_instance_agentpools_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AgentPool) GetMetadata() *api.Metadata {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return nil
}

func (x *AgentPool) GetSpec() *AgentPoolSpec {
	if x != nil {
		return x.xxx_hidden_Spec
	}
	return nil
}

func (x *AgentPool) GetStatus() *AgentPoolStatus {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return nil
}

func (x *AgentPool) SetMetadata(v *api.Metadata) {
	x.xxx_hidden_Metadata = v
}

func (x *AgentPool) SetSpec(v *AgentPoolSpec) {
	x.xxx_hidden_Spec = v
}

func (x *AgentPool) SetStatus(v *AgentPoolStatus) {
	x.xxx_hidden_Status = v
}

func (x *AgentPool) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Metadata != nil
}

func (x *AgentPool) HasSpec() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Spec != nil
}

func (x *AgentPool) HasStatus() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Status != nil
}

func (x *AgentPool) ClearMetadata() {
	x.xxx_hidden_Metadata = nil
}

func (x *AgentPool) ClearSpec() {
	x.xxx_hidden_Spec = nil
}

func (x *AgentPool) ClearStatus() {
	x.xxx_hidden_Status = nil
}

type AgentPool_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Metadata *api.Metadata
	Spec     *AgentPoolSpec
	Status   *AgentPoolStatus
}

func (b0 AgentPool_builder) Build() *AgentPool {
	m0 := &AgentPool{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Metadata = b.Metadata
	x.xxx_hidden_Spec = b.Spec
	x.xxx_hidden_Status = b.Status
	return m0
}

type AgentPoolSpec struct {
	state                          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ProjectId           *string                `protobuf:"bytes,1,opt,name=project_id,json=projectId"`
	xxx_hidden_Region              *string                `protobuf:"bytes,2,opt,name=region"`
	xxx_hidden_SubnetId            *string                `protobuf:"bytes,3,opt,name=subnet_id,json=subnetId"`
	xxx_hidden_Platform            *string                `protobuf:"bytes,4,opt,name=platform"`
	xxx_hidden_Preset              *string                `protobuf:"bytes,5,opt,name=preset"`
	xxx_hidden_ImageFamily         *string                `protobuf:"bytes,6,opt,name=image_family,json=imageFamily"`
	xxx_hidden_OsDiskSizeGibibytes int64                  `protobuf:"varint,7,opt,name=os_disk_size_gibibytes,json=osDiskSizeGibibytes"`
	xxx_hidden_Kubeadm             *kubeadm.Config        `protobuf:"bytes,8,opt,name=kubeadm"`
	xxx_hidden_Wireguard           *wireguard.Config      `protobuf:"bytes,9,opt,name=wireguard"`
	XXX_raceDetectHookData         protoimpl.RaceDetectHookData
	XXX_presence                   [1]uint32
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *AgentPoolSpec) Reset() {
	*x = AgentPoolSpec{}
	mi := &file_flex_plugin_pkg_services_agentpools_nebius_instance_agentpools_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentPoolSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentPoolSpec) ProtoMessage() {}

func (x *AgentPoolSpec) ProtoReflect() protoreflect.Message {
	mi := &file_flex_plugin_pkg_services_agentpools_nebius_instance_agentpools_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AgentPoolSpec) GetProjectId() string {
	if x != nil {
		if x.xxx_hidden_ProjectId != nil {
			return *x.xxx_hidden_ProjectId
		}
		return ""
	}
	return ""
}

func (x *AgentPoolSpec) GetRegion() string {
	if x != nil {
		if x.xxx_hidden_Region != nil {
			return *x.xxx_hidden_Region
		}
		return ""
	}
	return ""
}

func (x *AgentPoolSpec) GetSubnetId() string {
	if x != nil {
		if x.xxx_hidden_SubnetId != nil {
			return *x.xxx_hidden_SubnetId
		}
		return ""
	}
	return ""
}

func (x *AgentPoolSpec) GetPlatform() string {
	if x != nil {
		if x.xxx_hidden_Platform != nil {
			return *x.xxx_hidden_Platform
		}
		return ""
	}
	return ""
}

func (x *AgentPoolSpec) GetPreset() string {
	if x != nil {
		if x.xxx_hidden_Preset != nil {
			return *x.xxx_hidden_Preset
		}
		return ""
	}
	return ""
}

func (x *AgentPoolSpec) GetImageFamily() string {
	if x != nil {
		if x.xxx_hidden_ImageFamily != nil {
			return *x.xxx_hidden_ImageFamily
		}
		return ""
	}
	return ""
}

func (x *AgentPoolSpec) GetOsDiskSizeGibibytes() int64 {
	if x != nil {
		return x.xxx_hidden_OsDiskSizeGibibytes
	}
	return 0
}

func (x *AgentPoolSpec) GetKubeadm() *kubeadm.Config {
	if x != nil {
		return x.xxx_hidden_Kubeadm
	}
	return nil
}

func (x *AgentPoolSpec) GetWireguard() *wireguard.Config {
	if x != nil {
		return x.xxx_hidden_Wireguard
	}
	return nil
}

func (x *AgentPoolSpec) SetProjectId(v string) {
	x.xxx_hidden_ProjectId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 9)
}

func (x *AgentPoolSpec) SetRegion(v string) {
	x.xxx_hidden_Region = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 9)
}

func (x *AgentPoolSpec) SetSubnetId(v string) {
	x.xxx_hidden_SubnetId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 9)
}

func (x *AgentPoolSpec) SetPlatform(v string) {
	x.xxx_hidden_Platform = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 9)
}

func (x *AgentPoolSpec) SetPreset(v string) {
	x.xxx_hidden_Preset = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 9)
}

func (x *AgentPoolSpec) SetImageFamily(v string) {
	x.xxx_hidden_ImageFamily = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 9)
}

func (x *AgentPoolSpec) SetOsDiskSizeGibibytes(v int64) {
	x.xxx_hidden_OsDiskSizeGibibytes = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 9)
}

func (x *AgentPoolSpec) SetKubeadm(v *kubeadm.Config) {
	x.xxx_hidden_Kubeadm = v
}

func (x *AgentPoolSpec) SetWireguard(v *wireguard.Config) {
	x.xxx_hidden_Wireguard = v
}

func (x *AgentPoolSpec) HasProjectId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AgentPoolSpec) HasRegion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *AgentPoolSpec) HasSubnetId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *AgentPoolSpec) HasPlatform() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *AgentPoolSpec) HasPreset() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *AgentPoolSpec) HasImageFamily() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *AgentPoolSpec) HasOsDiskSizeGibibytes() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *AgentPoolSpec) HasKubeadm() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Kubeadm != nil
}

func (x *AgentPoolSpec) HasWireguard() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Wireguard != nil
}

func (x *AgentPoolSpec) ClearProjectId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_ProjectId = nil
}

func (x *AgentPoolSpec) ClearRegion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Region = nil
}

func (x *AgentPoolSpec) ClearSubnetId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_SubnetId = nil
}

func (x *AgentPoolSpec) ClearPlatform() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Platform = nil
}

func (x *AgentPoolSpec) ClearPreset() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Preset = nil
}

func (x *AgentPoolSpec) ClearImageFamily() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_ImageFamily = nil
}

func (x *AgentPoolSpec) ClearOsDiskSizeGibibytes() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_OsDiskSizeGibibytes = 0
}

func (x *AgentPoolSpec) ClearKubeadm() {
	x.xxx_hidden_Kubeadm = nil
}

func (x *AgentPoolSpec) ClearWireguard() {
	x.xxx_hidden_Wireguard = nil
}

type AgentPoolSpec_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ProjectId           *string
	Region              *string
	SubnetId            *string
	Platform            *string
	Preset              *string
	ImageFamily         *string
	OsDiskSizeGibibytes *int64
	Kubeadm             *kubeadm.Config
	Wireguard           *wireguard.Config
}

func (b0 AgentPoolSpec_builder) Build() *AgentPoolSpec {
	m0 := &AgentPoolSpec{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ProjectId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 9)
		x.xxx_hidden_ProjectId = b.ProjectId
	}
	if b.Region != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 9)
		x.xxx_hidden_Region = b.Region
	}
	if b.SubnetId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 9)
		x.xxx_hidden_SubnetId = b.SubnetId
	}
	if b.Platform != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 9)
		x.xxx_hidden_Platform = b.Platform
	}
	if b.Preset != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 9)
		x.xxx_hidden_Preset = b.Preset
	}
	if b.ImageFamily != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 9)
		x.xxx_hidden_ImageFamily = b.ImageFamily
	}
	if b.OsDiskSizeGibibytes != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 9)
		x.xxx_hidden_OsDiskSizeGibibytes = *b.OsDiskSizeGibibytes
	}
	x.xxx_hidden_Kubeadm = b.Kubeadm
	x.xxx_hidden_Wireguard = b.Wireguard
	return m0
}

type AgentPoolStatus struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_InstanceId  *string                `protobuf:"bytes,1,opt,name=instance_id,json=instanceId"`
	xxx_hidden_OsDiskId    *string                `protobuf:"bytes,2,opt,name=os_disk_id,json=osDiskId"`
	xxx_hidden_CreatedAt   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AgentPoolStatus) Reset() {
	*x = AgentPoolStatus{}
	mi := &file_flex_plugin_pkg_services_agentpools_nebius_instance_agentpools_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentPoolStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentPoolStatus) ProtoMessage() {}

func (x *AgentPoolStatus) ProtoReflect() protoreflect.Message {
	mi := &file_flex_plugin_pkg_services_agentpools_nebius_instance_agentpools_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AgentPoolStatus) GetInstanceId() string {
	if x != nil {
		if x.xxx_hidden_InstanceId != nil {
			return *x.xxx_hidden_InstanceId
		}
		return ""
	}
	return ""
}

func (x *AgentPoolStatus) GetOsDiskId() string {
	if x != nil {
		if x.xxx_hidden_OsDiskId != nil {
			return *x.xxx_hidden_OsDiskId
		}
		return ""
	}
	return ""
}

func (x *AgentPoolStatus) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CreatedAt
	}
	return nil
}

func (x *AgentPoolStatus) SetInstanceId(v string) {
	x.xxx_hidden_InstanceId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *AgentPoolStatus) SetOsDiskId(v string) {
	x.xxx_hidden_OsDiskId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *AgentPoolStatus) SetCreatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_CreatedAt = v
}

func (x *AgentPoolStatus) HasInstanceId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AgentPoolStatus) HasOsDiskId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *AgentPoolStatus) HasCreatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CreatedAt != nil
}

func (x *AgentPoolStatus) ClearInstanceId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_InstanceId = nil
}

func (x *AgentPoolStatus) ClearOsDiskId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_OsDiskId = nil
}

func (x *AgentPoolStatus) ClearCreatedAt() {
	x.xxx_hidden_CreatedAt = nil
}

type AgentPoolStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// instance id is the nebius side id of the instance.
	InstanceId *string
	// os disk id is the nebius side id of the os disk attached to the instance.
	OsDiskId  *string
	CreatedAt *timestamppb.Timestamp
}

func (b0 AgentPoolStatus_builder) Build() *AgentPoolStatus {
	m0 := &AgentPoolStatus{}
	b, x := &b0, m0
	_, _ = b, x
	if b.InstanceId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_InstanceId = b.InstanceId
	}
	if b.OsDiskId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_OsDiskId = b.OsDiskId
	}
	x.xxx_hidden_CreatedAt = b.CreatedAt
	return m0
}

var File_flex_plugin_pkg_services_agentpools_nebius_instance_agentpools_proto protoreflect.FileDescriptor

const file_flex_plugin_pkg_services_agentpools_nebius_instance_agentpools_proto_rawDesc = "" +
	"\n" +
	"Dplugin/pkg/services/agentpools/nebius/instance/agentpools.proto\x12\x1aagentpools.nebius.instance\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19plugin/api/api.proto\x1aFplugin/pkg/services/agentpools/api/features/kubeadm/kubeadm.proto\x1aJplugin/pkg/services/agentpools/api/features/wireguard/wireguard.proto\"\xba\x01\n" +
	"\tAgentPool\x12)\n" +
	"\bmetadata\x18\x01 \x01(\v2\r.api.MetadataR\bmetadata\x12=\n" +
	"\x04spec\x18\x02 \x01(\v2).agentpools.nebius.instance.AgentPoolSpecR\x04spec\x12C\n" +
	"\x06status\x18\x03 \x01(\v2+.agentpools.nebius.instance.AgentPoolStatusR\x06status\"\xcb\x02\n" +
	"\rAgentPoolSpec\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12\x1b\n" +
	"\tsubnet_id\x18\x03 \x01(\tR\bsubnetId\x12\x1a\n" +
	"\bplatform\x18\x04 \x01(\tR\bplatform\x12\x16\n" +
	"\x06preset\x18\x05 \x01(\tR\x06preset\x12!\n" +
	"\fimage_family\x18\x06 \x01(\tR\vimageFamily\x123\n" +
	"\x16os_disk_size_gibibytes\x18\a \x01(\x03R\x13osDiskSizeGibibytes\x12)\n" +
	"\akubeadm\x18\b \x01(\v2\x0f.kubeadm.ConfigR\akubeadm\x12/\n" +
	"\twireguard\x18\t \x01(\v2\x11.wireguard.ConfigR\twireguard\"\x8b\x01\n" +
	"\x0fAgentPoolStatus\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x1c\n" +
	"\n" +
	"os_disk_id\x18\x02 \x01(\tR\bosDiskId\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtBOZMgithub.com/Azure/aks-flex/plugin/pkg/services/agentpools/nebius/instanceb\beditionsp\xe9\a"

var file_flex_plugin_pkg_services_agentpools_nebius_instance_agentpools_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_flex_plugin_pkg_services_agentpools_nebius_instance_agentpools_proto_goTypes = []any{
	(*AgentPool)(nil),             // 0: agentpools.nebius.instance.AgentPool
	(*AgentPoolSpec)(nil),         // 1: agentpools.nebius.instance.AgentPoolSpec
	(*AgentPoolStatus)(nil),       // 2: agentpools.nebius.instance.AgentPoolStatus
	(*api.Metadata)(nil),          // 3: api.Metadata
	(*kubeadm.Config)(nil),        // 4: kubeadm.Config
	(*wireguard.Config)(nil),      // 5: wireguard.Config
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_flex_plugin_pkg_services_agentpools_nebius_instance_agentpools_proto_depIdxs = []int32{
	3, // 0: agentpools.nebius.instance.AgentPool.metadata:type_name -> api.Metadata
	1, // 1: agentpools.nebius.instance.AgentPool.spec:type_name -> agentpools.nebius.instance.AgentPoolSpec
	2, // 2: agentpools.nebius.instance.AgentPool.status:type_name -> agentpools.nebius.instance.AgentPoolStatus
	4, // 3: agentpools.nebius.instance.AgentPoolSpec.kubeadm:type_name -> kubeadm.Config
	5, // 4: agentpools.nebius.instance.AgentPoolSpec.wireguard:type_name -> wireguard.Config
	6, // 5: agentpools.nebius.instance.AgentPoolStatus.created_at:type_name -> google.protobuf.Timestamp
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_flex_plugin_pkg_services_agentpools_nebius_instance_agentpools_proto_init() }
func file_flex_plugin_pkg_services_agentpools_nebius_instance_agentpools_proto_init() {
	if File_flex_plugin_pkg_services_agentpools_nebius_instance_agentpools_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_flex_plugin_pkg_services_agentpools_nebius_instance_agentpools_proto_rawDesc), len(file_flex_plugin_pkg_services_agentpools_nebius_instance_agentpools_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_flex_plugin_pkg_services_agentpools_nebius_instance_agentpools_proto_goTypes,
		DependencyIndexes: file_flex_plugin_pkg_services_agentpools_nebius_instance_agentpools_proto_depIdxs,
		MessageInfos:      file_flex_plugin_pkg_services_agentpools_nebius_instance_agentpools_proto_msgTypes,
	}.Build()
	File_flex_plugin_pkg_services_agentpools_nebius_instance_agentpools_proto = out.File
	file_flex_plugin_pkg_services_agentpools_nebius_instance_agentpools_proto_goTypes = nil
	file_flex_plugin_pkg_services_agentpools_nebius_instance_agentpools_proto_depIdxs = nil
}
