// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: stretch/plugin/pkg/services/agentpools/api/features/arc/arc.proto

package arc

import (
	reflect "reflect"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Config struct {
	state                             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ResourceId             *string                `protobuf:"bytes,1,opt,name=resource_id,json=resourceId"`
	xxx_hidden_TenantId               *string                `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId"`
	xxx_hidden_ServicePrincipalId     *string                `protobuf:"bytes,3,opt,name=service_principal_id,json=servicePrincipalId"`
	xxx_hidden_ServicePrincipalSecret *string                `protobuf:"bytes,4,opt,name=service_principal_secret,json=servicePrincipalSecret"`
	XXX_raceDetectHookData            protoimpl.RaceDetectHookData
	XXX_presence                      [1]uint32
	unknownFields                     protoimpl.UnknownFields
	sizeCache                         protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_stretch_plugin_pkg_services_agentpools_api_features_arc_arc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_stretch_plugin_pkg_services_agentpools_api_features_arc_arc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Config) GetResourceId() string {
	if x != nil {
		if x.xxx_hidden_ResourceId != nil {
			return *x.xxx_hidden_ResourceId
		}
		return ""
	}
	return ""
}

func (x *Config) GetTenantId() string {
	if x != nil {
		if x.xxx_hidden_TenantId != nil {
			return *x.xxx_hidden_TenantId
		}
		return ""
	}
	return ""
}

func (x *Config) GetServicePrincipalId() string {
	if x != nil {
		if x.xxx_hidden_ServicePrincipalId != nil {
			return *x.xxx_hidden_ServicePrincipalId
		}
		return ""
	}
	return ""
}

func (x *Config) GetServicePrincipalSecret() string {
	if x != nil {
		if x.xxx_hidden_ServicePrincipalSecret != nil {
			return *x.xxx_hidden_ServicePrincipalSecret
		}
		return ""
	}
	return ""
}

func (x *Config) SetResourceId(v string) {
	x.xxx_hidden_ResourceId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *Config) SetTenantId(v string) {
	x.xxx_hidden_TenantId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *Config) SetServicePrincipalId(v string) {
	x.xxx_hidden_ServicePrincipalId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *Config) SetServicePrincipalSecret(v string) {
	x.xxx_hidden_ServicePrincipalSecret = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *Config) HasResourceId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Config) HasTenantId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Config) HasServicePrincipalId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Config) HasServicePrincipalSecret() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Config) ClearResourceId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_ResourceId = nil
}

func (x *Config) ClearTenantId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_TenantId = nil
}

func (x *Config) ClearServicePrincipalId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_ServicePrincipalId = nil
}

func (x *Config) ClearServicePrincipalSecret() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_ServicePrincipalSecret = nil
}

type Config_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ResourceId             *string
	TenantId               *string
	ServicePrincipalId     *string
	ServicePrincipalSecret *string
}

func (b0 Config_builder) Build() *Config {
	m0 := &Config{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ResourceId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_ResourceId = b.ResourceId
	}
	if b.TenantId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_TenantId = b.TenantId
	}
	if b.ServicePrincipalId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_ServicePrincipalId = b.ServicePrincipalId
	}
	if b.ServicePrincipalSecret != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_ServicePrincipalSecret = b.ServicePrincipalSecret
	}
	return m0
}

var File_stretch_plugin_pkg_services_agentpools_api_features_arc_arc_proto protoreflect.FileDescriptor

const file_stretch_plugin_pkg_services_agentpools_api_features_arc_arc_proto_rawDesc = "" +
	"\n" +
	"Astretch/plugin/pkg/services/agentpools/api/features/arc/arc.proto\x12\x03arc\"\xb2\x01\n" +
	"\x06Config\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x120\n" +
	"\x14service_principal_id\x18\x03 \x01(\tR\x12servicePrincipalId\x128\n" +
	"\x18service_principal_secret\x18\x04 \x01(\tR\x16servicePrincipalSecretBqZogithub.com/Azure/aks-flex/flex-plugin/pkg/services/agentpools/api/features/arcb\beditionsp\xe9\a"

var file_stretch_plugin_pkg_services_agentpools_api_features_arc_arc_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_stretch_plugin_pkg_services_agentpools_api_features_arc_arc_proto_goTypes = []any{
	(*Config)(nil), // 0: arc.Config
}
var file_stretch_plugin_pkg_services_agentpools_api_features_arc_arc_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_stretch_plugin_pkg_services_agentpools_api_features_arc_arc_proto_init() }
func file_stretch_plugin_pkg_services_agentpools_api_features_arc_arc_proto_init() {
	if File_stretch_plugin_pkg_services_agentpools_api_features_arc_arc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stretch_plugin_pkg_services_agentpools_api_features_arc_arc_proto_rawDesc), len(file_stretch_plugin_pkg_services_agentpools_api_features_arc_arc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_stretch_plugin_pkg_services_agentpools_api_features_arc_arc_proto_goTypes,
		DependencyIndexes: file_stretch_plugin_pkg_services_agentpools_api_features_arc_arc_proto_depIdxs,
		MessageInfos:      file_stretch_plugin_pkg_services_agentpools_api_features_arc_arc_proto_msgTypes,
	}.Build()
	File_stretch_plugin_pkg_services_agentpools_api_features_arc_arc_proto = out.File
	file_stretch_plugin_pkg_services_agentpools_api_features_arc_arc_proto_goTypes = nil
	file_stretch_plugin_pkg_services_agentpools_api_features_arc_arc_proto_depIdxs = nil
}
