apiVersion: unbounded.aks.azure.com/v1alpha1
kind: Site
metadata:
  name: site-azure
spec:
  nodeCidrs:
    - "172.16.0.0/16" # Should match the VNet address space on the Azure side
  podCidrAssignments:
    - assignmentEnabled: true
      cidrBlocks:
        - "10.100.0.0/16" # Pod CIDR range for this site
      nodeBlockSizes:
        ipv4: 24
      priority: 100
---
apiVersion: unbounded.aks.azure.com/v1alpha1
kind: SiteGatewayPoolAssignment
metadata:
  name: main-gateway-site-azure
spec:
  sites:
    - "site-azure"
  gatewayPools:
    - "main-gateways"
