apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: azure-gpu-nodepool
spec:
  template:
    metadata:
      labels:
        nodepool: azure-gpu-nodepool
        nvidia.com/gpu.present: "true"
    spec:
      nodeClassRef:
        group: karpenter.azure.com
        kind: AKSNodeClass
        name: azure
      requirements:
        - key: node.kubernetes.io/instance-type
          operator: In
          values: ["Standard_ND96isr_H100_v5"]
  limits:
    cpu: "1000"
    memory: 10000Gi
    nvidia.com/gpu: "64"
