apiVersion: unbounded.aks.azure.com/v1alpha1
kind: Site
metadata:
  name: {{ .Name }}
spec:
  nodeCidrs:
    - "{{ .NodeCIDR }}" # Should match the private network space in the environment
  podCidrAssignments:
    - assignmentEnabled: true
      cidrBlocks:
        - "{{ .PodCIDR }}" # Pod CIDR range for this site
      nodeBlockSizes:
        ipv4: 24
      priority: 100
---
apiVersion: unbounded.aks.azure.com/v1alpha1
kind: SiteGatewayPoolAssignment
metadata:
  name: main-gateway-{{ .Name }}
spec:
  sites:
    - "{{ .Name }}"
  gatewayPools:
    - "main-gateways"
