// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: flex-plugin/pkg/services/agentpools/api/features/kubeadm/kubeadm.proto

package kubeadm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Taint struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Key         *string                `protobuf:"bytes,1,opt,name=key"`
	xxx_hidden_Value       *string                `protobuf:"bytes,2,opt,name=value"`
	xxx_hidden_Effect      *string                `protobuf:"bytes,3,opt,name=effect"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Taint) Reset() {
	*x = Taint{}
	mi := &file_flex_plugin_pkg_services_agentpools_api_features_kubeadm_kubeadm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Taint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Taint) ProtoMessage() {}

func (x *Taint) ProtoReflect() protoreflect.Message {
	mi := &file_flex_plugin_pkg_services_agentpools_api_features_kubeadm_kubeadm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Taint) GetKey() string {
	if x != nil {
		if x.xxx_hidden_Key != nil {
			return *x.xxx_hidden_Key
		}
		return ""
	}
	return ""
}

func (x *Taint) GetValue() string {
	if x != nil {
		if x.xxx_hidden_Value != nil {
			return *x.xxx_hidden_Value
		}
		return ""
	}
	return ""
}

func (x *Taint) GetEffect() string {
	if x != nil {
		if x.xxx_hidden_Effect != nil {
			return *x.xxx_hidden_Effect
		}
		return ""
	}
	return ""
}

func (x *Taint) SetKey(v string) {
	x.xxx_hidden_Key = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *Taint) SetValue(v string) {
	x.xxx_hidden_Value = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *Taint) SetEffect(v string) {
	x.xxx_hidden_Effect = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *Taint) HasKey() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Taint) HasValue() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Taint) HasEffect() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Taint) ClearKey() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Key = nil
}

func (x *Taint) ClearValue() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Value = nil
}

func (x *Taint) ClearEffect() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Effect = nil
}

type Taint_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Key    *string
	Value  *string
	Effect *string
}

func (b0 Taint_builder) Build() *Taint {
	m0 := &Taint{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Key != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Key = b.Key
	}
	if b.Value != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Value = b.Value
	}
	if b.Effect != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Effect = b.Effect
	}
	return m0
}

type Config struct {
	state                               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Server                   *string                `protobuf:"bytes,1,opt,name=server"`
	xxx_hidden_CertificateAuthorityData []byte                 `protobuf:"bytes,2,opt,name=certificate_authority_data,json=certificateAuthorityData"`
	xxx_hidden_Token                    *string                `protobuf:"bytes,3,opt,name=token"`
	xxx_hidden_NodeLabels               map[string]string      `protobuf:"bytes,4,rep,name=node_labels,json=nodeLabels" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_NodeIp                   *string                `protobuf:"bytes,5,opt,name=node_ip,json=nodeIp"`
	xxx_hidden_RegisterWithTaints       *[]*Taint              `protobuf:"bytes,6,rep,name=register_with_taints,json=registerWithTaints"`
	XXX_raceDetectHookData              protoimpl.RaceDetectHookData
	XXX_presence                        [1]uint32
	unknownFields                       protoimpl.UnknownFields
	sizeCache                           protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_flex_plugin_pkg_services_agentpools_api_features_kubeadm_kubeadm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_flex_plugin_pkg_services_agentpools_api_features_kubeadm_kubeadm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Config) GetServer() string {
	if x != nil {
		if x.xxx_hidden_Server != nil {
			return *x.xxx_hidden_Server
		}
		return ""
	}
	return ""
}

func (x *Config) GetCertificateAuthorityData() []byte {
	if x != nil {
		return x.xxx_hidden_CertificateAuthorityData
	}
	return nil
}

func (x *Config) GetToken() string {
	if x != nil {
		if x.xxx_hidden_Token != nil {
			return *x.xxx_hidden_Token
		}
		return ""
	}
	return ""
}

func (x *Config) GetNodeLabels() map[string]string {
	if x != nil {
		return x.xxx_hidden_NodeLabels
	}
	return nil
}

func (x *Config) GetNodeIp() string {
	if x != nil {
		if x.xxx_hidden_NodeIp != nil {
			return *x.xxx_hidden_NodeIp
		}
		return ""
	}
	return ""
}

func (x *Config) GetRegisterWithTaints() []*Taint {
	if x != nil {
		if x.xxx_hidden_RegisterWithTaints != nil {
			return *x.xxx_hidden_RegisterWithTaints
		}
	}
	return nil
}

func (x *Config) SetServer(v string) {
	x.xxx_hidden_Server = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 6)
}

func (x *Config) SetCertificateAuthorityData(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_CertificateAuthorityData = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 6)
}

func (x *Config) SetToken(v string) {
	x.xxx_hidden_Token = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 6)
}

func (x *Config) SetNodeLabels(v map[string]string) {
	x.xxx_hidden_NodeLabels = v
}

func (x *Config) SetNodeIp(v string) {
	x.xxx_hidden_NodeIp = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 6)
}

func (x *Config) SetRegisterWithTaints(v []*Taint) {
	x.xxx_hidden_RegisterWithTaints = &v
}

func (x *Config) HasServer() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Config) HasCertificateAuthorityData() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Config) HasToken() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Config) HasNodeIp() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *Config) ClearServer() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Server = nil
}

func (x *Config) ClearCertificateAuthorityData() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_CertificateAuthorityData = nil
}

func (x *Config) ClearToken() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Token = nil
}

func (x *Config) ClearNodeIp() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_NodeIp = nil
}

type Config_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Server                   *string
	CertificateAuthorityData []byte
	Token                    *string
	// List of node labels to assign using the kubelet flag
	NodeLabels map[string]string
	// WireGuard IP for --node-ip kubelet argument (optional)
	NodeIp *string
	// List of taints to assign using the kubelet flag, in the format "key=value:effect"
	RegisterWithTaints []*Taint
}

func (b0 Config_builder) Build() *Config {
	m0 := &Config{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Server != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 6)
		x.xxx_hidden_Server = b.Server
	}
	if b.CertificateAuthorityData != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 6)
		x.xxx_hidden_CertificateAuthorityData = b.CertificateAuthorityData
	}
	if b.Token != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 6)
		x.xxx_hidden_Token = b.Token
	}
	x.xxx_hidden_NodeLabels = b.NodeLabels
	if b.NodeIp != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 6)
		x.xxx_hidden_NodeIp = b.NodeIp
	}
	x.xxx_hidden_RegisterWithTaints = &b.RegisterWithTaints
	return m0
}

var File_flex_plugin_pkg_services_agentpools_api_features_kubeadm_kubeadm_proto protoreflect.FileDescriptor

const file_flex_plugin_pkg_services_agentpools_api_features_kubeadm_kubeadm_proto_rawDesc = "" +
	"\n" +
	"Fflex-plugin/pkg/services/agentpools/api/features/kubeadm/kubeadm.proto\x12\akubeadm\"G\n" +
	"\x05Taint\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x16\n" +
	"\x06effect\x18\x03 \x01(\tR\x06effect\"\xd0\x02\n" +
	"\x06Config\x12\x16\n" +
	"\x06server\x18\x01 \x01(\tR\x06server\x12<\n" +
	"\x1acertificate_authority_data\x18\x02 \x01(\fR\x18certificateAuthorityData\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12@\n" +
	"\vnode_labels\x18\x04 \x03(\v2\x1f.kubeadm.Config.NodeLabelsEntryR\n" +
	"nodeLabels\x12\x17\n" +
	"\anode_ip\x18\x05 \x01(\tR\x06nodeIp\x12@\n" +
	"\x14register_with_taints\x18\x06 \x03(\v2\x0e.kubeadm.TaintR\x12registerWithTaints\x1a=\n" +
	"\x0fNodeLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01BTZRgithub.com/Azure/aks-flex/flex-plugin/pkg/services/agentpools/api/features/kubeadmb\beditionsp\xe9\a"

var file_flex_plugin_pkg_services_agentpools_api_features_kubeadm_kubeadm_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_flex_plugin_pkg_services_agentpools_api_features_kubeadm_kubeadm_proto_goTypes = []any{
	(*Taint)(nil),  // 0: kubeadm.Taint
	(*Config)(nil), // 1: kubeadm.Config
	nil,            // 2: kubeadm.Config.NodeLabelsEntry
}
var file_flex_plugin_pkg_services_agentpools_api_features_kubeadm_kubeadm_proto_depIdxs = []int32{
	2, // 0: kubeadm.Config.node_labels:type_name -> kubeadm.Config.NodeLabelsEntry
	0, // 1: kubeadm.Config.register_with_taints:type_name -> kubeadm.Taint
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_flex_plugin_pkg_services_agentpools_api_features_kubeadm_kubeadm_proto_init() }
func file_flex_plugin_pkg_services_agentpools_api_features_kubeadm_kubeadm_proto_init() {
	if File_flex_plugin_pkg_services_agentpools_api_features_kubeadm_kubeadm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_flex_plugin_pkg_services_agentpools_api_features_kubeadm_kubeadm_proto_rawDesc), len(file_flex_plugin_pkg_services_agentpools_api_features_kubeadm_kubeadm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_flex_plugin_pkg_services_agentpools_api_features_kubeadm_kubeadm_proto_goTypes,
		DependencyIndexes: file_flex_plugin_pkg_services_agentpools_api_features_kubeadm_kubeadm_proto_depIdxs,
		MessageInfos:      file_flex_plugin_pkg_services_agentpools_api_features_kubeadm_kubeadm_proto_msgTypes,
	}.Build()
	File_flex_plugin_pkg_services_agentpools_api_features_kubeadm_kubeadm_proto = out.File
	file_flex_plugin_pkg_services_agentpools_api_features_kubeadm_kubeadm_proto_goTypes = nil
	file_flex_plugin_pkg_services_agentpools_api_features_kubeadm_kubeadm_proto_depIdxs = nil
}
