// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: plugin/pkg/db/internal/testobj/testobj.proto

package testobj

import (
	api "github.com/Azure/aks-flex/plugin/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FakeObject struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Metadata *api.Metadata          `protobuf:"bytes,1,opt,name=metadata"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *FakeObject) Reset() {
	*x = FakeObject{}
	mi := &file_flex_plugin_pkg_db_internal_testobj_testobj_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FakeObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FakeObject) ProtoMessage() {}

func (x *FakeObject) ProtoReflect() protoreflect.Message {
	mi := &file_flex_plugin_pkg_db_internal_testobj_testobj_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *FakeObject) GetMetadata() *api.Metadata {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return nil
}

func (x *FakeObject) SetMetadata(v *api.Metadata) {
	x.xxx_hidden_Metadata = v
}

func (x *FakeObject) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Metadata != nil
}

func (x *FakeObject) ClearMetadata() {
	x.xxx_hidden_Metadata = nil
}

type FakeObject_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Metadata *api.Metadata
}

func (b0 FakeObject_builder) Build() *FakeObject {
	m0 := &FakeObject{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Metadata = b.Metadata
	return m0
}

var File_flex_plugin_pkg_db_internal_testobj_testobj_proto protoreflect.FileDescriptor

const file_flex_plugin_pkg_db_internal_testobj_testobj_proto_rawDesc = "" +
	"\n" +
	"1plugin/pkg/db/internal/testobj/testobj.proto\x12\atestobj\x1a\x19plugin/api/api.proto\"7\n" +
	"\n" +
	"FakeObject\x12)\n" +
	"\bmetadata\x18\x01 \x01(\v2\r.api.MetadataR\bmetadataB?Z=github.com/Azure/aks-flex/plugin/pkg/db/internal/testobjb\beditionsp\xe9\a"

var file_flex_plugin_pkg_db_internal_testobj_testobj_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_flex_plugin_pkg_db_internal_testobj_testobj_proto_goTypes = []any{
	(*FakeObject)(nil),   // 0: testobj.FakeObject
	(*api.Metadata)(nil), // 1: api.Metadata
}
var file_flex_plugin_pkg_db_internal_testobj_testobj_proto_depIdxs = []int32{
	1, // 0: testobj.FakeObject.metadata:type_name -> api.Metadata
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_flex_plugin_pkg_db_internal_testobj_testobj_proto_init() }
func file_flex_plugin_pkg_db_internal_testobj_testobj_proto_init() {
	if File_flex_plugin_pkg_db_internal_testobj_testobj_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_flex_plugin_pkg_db_internal_testobj_testobj_proto_rawDesc), len(file_flex_plugin_pkg_db_internal_testobj_testobj_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_flex_plugin_pkg_db_internal_testobj_testobj_proto_goTypes,
		DependencyIndexes: file_flex_plugin_pkg_db_internal_testobj_testobj_proto_depIdxs,
		MessageInfos:      file_flex_plugin_pkg_db_internal_testobj_testobj_proto_msgTypes,
	}.Build()
	File_flex_plugin_pkg_db_internal_testobj_testobj_proto = out.File
	file_flex_plugin_pkg_db_internal_testobj_testobj_proto_goTypes = nil
	file_flex_plugin_pkg_db_internal_testobj_testobj_proto_depIdxs = nil
}
