---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: unbounded-cni-controller
  namespace: unbounded-cni
  labels:
    app.kubernetes.io/name: unbounded-cni-controller
    app.kubernetes.io/component: controller
