apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00-namespace.yaml
  - 01-configmap.yaml
  - crds/unbounded.aks.azure.com_gatewaypoolnodes.yaml
  - crds/unbounded.aks.azure.com_gatewaypoolpeerings.yaml
  - crds/unbounded.aks.azure.com_gatewaypools.yaml
  - crds/unbounded.aks.azure.com_sitegatewaypoolassignments.yaml
  - crds/unbounded.aks.azure.com_sitenodeslices.yaml
  - crds/unbounded.aks.azure.com_sitepeerings.yaml
  - crds/unbounded.aks.azure.com_sites.yaml
  - controller/01-serviceaccount.yaml
  - controller/02-rbac.yaml
  - controller/03-deployment.yaml
  - controller/04-service.yaml
  - controller/05-webhook.yaml
  - node/00-frr-configmap.yaml
  - node/01-serviceaccount.yaml
  - node/02-rbac.yaml
  - node/03-daemonset.yaml
