// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: stretch/plugin/pkg/services/agentpools/azure/ubuntu2404vmss/agentpools.proto

package ubuntu2404vmss

import (
	reflect "reflect"
	unsafe "unsafe"

	api "github.com/Azure/aks-flex/flex-plugin/api"
	capacity "github.com/Azure/aks-flex/flex-plugin/pkg/services/agentpools/api/features/capacity"
	kubeadm "github.com/Azure/aks-flex/flex-plugin/pkg/services/agentpools/api/features/kubeadm"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentPool struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Metadata *api.Metadata          `protobuf:"bytes,1,opt,name=metadata"`
	xxx_hidden_Spec     *AgentPoolSpec         `protobuf:"bytes,2,opt,name=spec"`
	xxx_hidden_Status   *AgentPoolStatus       `protobuf:"bytes,3,opt,name=status"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AgentPool) Reset() {
	*x = AgentPool{}
	mi := &file_stretch_plugin_pkg_services_agentpools_azure_ubuntu2404vmss_agentpools_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentPool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentPool) ProtoMessage() {}

func (x *AgentPool) ProtoReflect() protoreflect.Message {
	mi := &file_stretch_plugin_pkg_services_agentpools_azure_ubuntu2404vmss_agentpools_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AgentPool) GetMetadata() *api.Metadata {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return nil
}

func (x *AgentPool) GetSpec() *AgentPoolSpec {
	if x != nil {
		return x.xxx_hidden_Spec
	}
	return nil
}

func (x *AgentPool) GetStatus() *AgentPoolStatus {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return nil
}

func (x *AgentPool) SetMetadata(v *api.Metadata) {
	x.xxx_hidden_Metadata = v
}

func (x *AgentPool) SetSpec(v *AgentPoolSpec) {
	x.xxx_hidden_Spec = v
}

func (x *AgentPool) SetStatus(v *AgentPoolStatus) {
	x.xxx_hidden_Status = v
}

func (x *AgentPool) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Metadata != nil
}

func (x *AgentPool) HasSpec() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Spec != nil
}

func (x *AgentPool) HasStatus() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Status != nil
}

func (x *AgentPool) ClearMetadata() {
	x.xxx_hidden_Metadata = nil
}

func (x *AgentPool) ClearSpec() {
	x.xxx_hidden_Spec = nil
}

func (x *AgentPool) ClearStatus() {
	x.xxx_hidden_Status = nil
}

type AgentPool_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Metadata *api.Metadata
	Spec     *AgentPoolSpec
	Status   *AgentPoolStatus
}

func (b0 AgentPool_builder) Build() *AgentPool {
	m0 := &AgentPool{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Metadata = b.Metadata
	x.xxx_hidden_Spec = b.Spec
	x.xxx_hidden_Status = b.Status
	return m0
}

type AgentPoolSpec struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ResourceId  *string                `protobuf:"bytes,1,opt,name=resource_id,json=resourceId"`
	xxx_hidden_Location    *string                `protobuf:"bytes,2,opt,name=location"`
	xxx_hidden_SubnetId    *string                `protobuf:"bytes,3,opt,name=subnet_id,json=subnetId"`
	xxx_hidden_Sku         *string                `protobuf:"bytes,4,opt,name=sku"`
	xxx_hidden_Capacity    *capacity.Config       `protobuf:"bytes,5,opt,name=capacity"`
	xxx_hidden_Kubeadm     *kubeadm.Config        `protobuf:"bytes,6,opt,name=kubeadm"`
	xxx_hidden_Zones       []string               `protobuf:"bytes,7,rep,name=zones"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AgentPoolSpec) Reset() {
	*x = AgentPoolSpec{}
	mi := &file_stretch_plugin_pkg_services_agentpools_azure_ubuntu2404vmss_agentpools_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentPoolSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentPoolSpec) ProtoMessage() {}

func (x *AgentPoolSpec) ProtoReflect() protoreflect.Message {
	mi := &file_stretch_plugin_pkg_services_agentpools_azure_ubuntu2404vmss_agentpools_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AgentPoolSpec) GetResourceId() string {
	if x != nil {
		if x.xxx_hidden_ResourceId != nil {
			return *x.xxx_hidden_ResourceId
		}
		return ""
	}
	return ""
}

func (x *AgentPoolSpec) GetLocation() string {
	if x != nil {
		if x.xxx_hidden_Location != nil {
			return *x.xxx_hidden_Location
		}
		return ""
	}
	return ""
}

func (x *AgentPoolSpec) GetSubnetId() string {
	if x != nil {
		if x.xxx_hidden_SubnetId != nil {
			return *x.xxx_hidden_SubnetId
		}
		return ""
	}
	return ""
}

func (x *AgentPoolSpec) GetSku() string {
	if x != nil {
		if x.xxx_hidden_Sku != nil {
			return *x.xxx_hidden_Sku
		}
		return ""
	}
	return ""
}

func (x *AgentPoolSpec) GetCapacity() *capacity.Config {
	if x != nil {
		return x.xxx_hidden_Capacity
	}
	return nil
}

func (x *AgentPoolSpec) GetKubeadm() *kubeadm.Config {
	if x != nil {
		return x.xxx_hidden_Kubeadm
	}
	return nil
}

func (x *AgentPoolSpec) GetZones() []string {
	if x != nil {
		return x.xxx_hidden_Zones
	}
	return nil
}

func (x *AgentPoolSpec) SetResourceId(v string) {
	x.xxx_hidden_ResourceId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 7)
}

func (x *AgentPoolSpec) SetLocation(v string) {
	x.xxx_hidden_Location = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 7)
}

func (x *AgentPoolSpec) SetSubnetId(v string) {
	x.xxx_hidden_SubnetId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 7)
}

func (x *AgentPoolSpec) SetSku(v string) {
	x.xxx_hidden_Sku = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 7)
}

func (x *AgentPoolSpec) SetCapacity(v *capacity.Config) {
	x.xxx_hidden_Capacity = v
}

func (x *AgentPoolSpec) SetKubeadm(v *kubeadm.Config) {
	x.xxx_hidden_Kubeadm = v
}

func (x *AgentPoolSpec) SetZones(v []string) {
	x.xxx_hidden_Zones = v
}

func (x *AgentPoolSpec) HasResourceId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AgentPoolSpec) HasLocation() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *AgentPoolSpec) HasSubnetId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *AgentPoolSpec) HasSku() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *AgentPoolSpec) HasCapacity() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Capacity != nil
}

func (x *AgentPoolSpec) HasKubeadm() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Kubeadm != nil
}

func (x *AgentPoolSpec) ClearResourceId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_ResourceId = nil
}

func (x *AgentPoolSpec) ClearLocation() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Location = nil
}

func (x *AgentPoolSpec) ClearSubnetId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_SubnetId = nil
}

func (x *AgentPoolSpec) ClearSku() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Sku = nil
}

func (x *AgentPoolSpec) ClearCapacity() {
	x.xxx_hidden_Capacity = nil
}

func (x *AgentPoolSpec) ClearKubeadm() {
	x.xxx_hidden_Kubeadm = nil
}

type AgentPoolSpec_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ResourceId *string
	Location   *string
	SubnetId   *string
	Sku        *string
	Capacity   *capacity.Config
	Kubeadm    *kubeadm.Config
	Zones      []string
}

func (b0 AgentPoolSpec_builder) Build() *AgentPoolSpec {
	m0 := &AgentPoolSpec{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ResourceId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 7)
		x.xxx_hidden_ResourceId = b.ResourceId
	}
	if b.Location != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 7)
		x.xxx_hidden_Location = b.Location
	}
	if b.SubnetId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 7)
		x.xxx_hidden_SubnetId = b.SubnetId
	}
	if b.Sku != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 7)
		x.xxx_hidden_Sku = b.Sku
	}
	x.xxx_hidden_Capacity = b.Capacity
	x.xxx_hidden_Kubeadm = b.Kubeadm
	x.xxx_hidden_Zones = b.Zones
	return m0
}

type AgentPoolStatus struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentPoolStatus) Reset() {
	*x = AgentPoolStatus{}
	mi := &file_stretch_plugin_pkg_services_agentpools_azure_ubuntu2404vmss_agentpools_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentPoolStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentPoolStatus) ProtoMessage() {}

func (x *AgentPoolStatus) ProtoReflect() protoreflect.Message {
	mi := &file_stretch_plugin_pkg_services_agentpools_azure_ubuntu2404vmss_agentpools_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type AgentPoolStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 AgentPoolStatus_builder) Build() *AgentPoolStatus {
	m0 := &AgentPoolStatus{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_stretch_plugin_pkg_services_agentpools_azure_ubuntu2404vmss_agentpools_proto protoreflect.FileDescriptor

const file_stretch_plugin_pkg_services_agentpools_azure_ubuntu2404vmss_agentpools_proto_rawDesc = "" +
	"\n" +
	"Lstretch/plugin/pkg/services/agentpools/azure/ubuntu2404vmss/agentpools.proto\x12\x1fagentpools.azure.ubuntu2404vmss\x1a\x1cstretch/plugin/api/api.proto\x1aKstretch/plugin/pkg/services/agentpools/api/features/capacity/capacity.proto\x1aIstretch/plugin/pkg/services/agentpools/api/features/kubeadm/kubeadm.proto\"\xc4\x01\n" +
	"\tAgentPool\x12)\n" +
	"\bmetadata\x18\x01 \x01(\v2\r.api.MetadataR\bmetadata\x12B\n" +
	"\x04spec\x18\x02 \x01(\v2..agentpools.azure.ubuntu2404vmss.AgentPoolSpecR\x04spec\x12H\n" +
	"\x06status\x18\x03 \x01(\v20.agentpools.azure.ubuntu2404vmss.AgentPoolStatusR\x06status\"\xea\x01\n" +
	"\rAgentPoolSpec\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\x12\x1a\n" +
	"\blocation\x18\x02 \x01(\tR\blocation\x12\x1b\n" +
	"\tsubnet_id\x18\x03 \x01(\tR\bsubnetId\x12\x10\n" +
	"\x03sku\x18\x04 \x01(\tR\x03sku\x12,\n" +
	"\bcapacity\x18\x05 \x01(\v2\x10.capacity.ConfigR\bcapacity\x12)\n" +
	"\akubeadm\x18\x06 \x01(\v2\x0f.kubeadm.ConfigR\akubeadm\x12\x14\n" +
	"\x05zones\x18\a \x03(\tR\x05zones\"\x11\n" +
	"\x0fAgentPoolStatusBuZsgithub.com/Azure/aks-flex/flex-plugin/pkg/services/agentpools/azure/ubuntu2404vmssb\beditionsp\xe9\a"

var file_stretch_plugin_pkg_services_agentpools_azure_ubuntu2404vmss_agentpools_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_stretch_plugin_pkg_services_agentpools_azure_ubuntu2404vmss_agentpools_proto_goTypes = []any{
	(*AgentPool)(nil),       // 0: agentpools.azure.ubuntu2404vmss.AgentPool
	(*AgentPoolSpec)(nil),   // 1: agentpools.azure.ubuntu2404vmss.AgentPoolSpec
	(*AgentPoolStatus)(nil), // 2: agentpools.azure.ubuntu2404vmss.AgentPoolStatus
	(*api.Metadata)(nil),    // 3: api.Metadata
	(*capacity.Config)(nil), // 4: capacity.Config
	(*kubeadm.Config)(nil),  // 5: kubeadm.Config
}
var file_stretch_plugin_pkg_services_agentpools_azure_ubuntu2404vmss_agentpools_proto_depIdxs = []int32{
	3, // 0: agentpools.azure.ubuntu2404vmss.AgentPool.metadata:type_name -> api.Metadata
	1, // 1: agentpools.azure.ubuntu2404vmss.AgentPool.spec:type_name -> agentpools.azure.ubuntu2404vmss.AgentPoolSpec
	2, // 2: agentpools.azure.ubuntu2404vmss.AgentPool.status:type_name -> agentpools.azure.ubuntu2404vmss.AgentPoolStatus
	4, // 3: agentpools.azure.ubuntu2404vmss.AgentPoolSpec.capacity:type_name -> capacity.Config
	5, // 4: agentpools.azure.ubuntu2404vmss.AgentPoolSpec.kubeadm:type_name -> kubeadm.Config
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_stretch_plugin_pkg_services_agentpools_azure_ubuntu2404vmss_agentpools_proto_init() }
func file_stretch_plugin_pkg_services_agentpools_azure_ubuntu2404vmss_agentpools_proto_init() {
	if File_stretch_plugin_pkg_services_agentpools_azure_ubuntu2404vmss_agentpools_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stretch_plugin_pkg_services_agentpools_azure_ubuntu2404vmss_agentpools_proto_rawDesc), len(file_stretch_plugin_pkg_services_agentpools_azure_ubuntu2404vmss_agentpools_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_stretch_plugin_pkg_services_agentpools_azure_ubuntu2404vmss_agentpools_proto_goTypes,
		DependencyIndexes: file_stretch_plugin_pkg_services_agentpools_azure_ubuntu2404vmss_agentpools_proto_depIdxs,
		MessageInfos:      file_stretch_plugin_pkg_services_agentpools_azure_ubuntu2404vmss_agentpools_proto_msgTypes,
	}.Build()
	File_stretch_plugin_pkg_services_agentpools_azure_ubuntu2404vmss_agentpools_proto = out.File
	file_stretch_plugin_pkg_services_agentpools_azure_ubuntu2404vmss_agentpools_proto_goTypes = nil
	file_stretch_plugin_pkg_services_agentpools_azure_ubuntu2404vmss_agentpools_proto_depIdxs = nil
}
