// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: flex-plugin/pkg/services/agentpools/api/agentpools.proto

package api

import (
	context "context"
	api "github.com/Azure/aks-flex/flex-plugin/api"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentPools_CreateOrUpdate_FullMethodName = "/agentpools.AgentPools/CreateOrUpdate"
	AgentPools_List_FullMethodName           = "/agentpools.AgentPools/List"
	AgentPools_Get_FullMethodName            = "/agentpools.AgentPools/Get"
	AgentPools_Delete_FullMethodName         = "/agentpools.AgentPools/Delete"
)

// AgentPoolsClient is the client API for AgentPools service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentPoolsClient interface {
	CreateOrUpdate(ctx context.Context, in *api.CreateOrUpdateRequest, opts ...grpc.CallOption) (*api.CreateOrUpdateResponse, error)
	List(ctx context.Context, in *api.ListRequest, opts ...grpc.CallOption) (*api.ListResponse, error)
	Get(ctx context.Context, in *api.GetRequest, opts ...grpc.CallOption) (*api.GetResponse, error)
	Delete(ctx context.Context, in *api.DeleteRequest, opts ...grpc.CallOption) (*api.DeleteResponse, error)
}

type agentPoolsClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentPoolsClient(cc grpc.ClientConnInterface) AgentPoolsClient {
	return &agentPoolsClient{cc}
}

func (c *agentPoolsClient) CreateOrUpdate(ctx context.Context, in *api.CreateOrUpdateRequest, opts ...grpc.CallOption) (*api.CreateOrUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(api.CreateOrUpdateResponse)
	err := c.cc.Invoke(ctx, AgentPools_CreateOrUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentPoolsClient) List(ctx context.Context, in *api.ListRequest, opts ...grpc.CallOption) (*api.ListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(api.ListResponse)
	err := c.cc.Invoke(ctx, AgentPools_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentPoolsClient) Get(ctx context.Context, in *api.GetRequest, opts ...grpc.CallOption) (*api.GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(api.GetResponse)
	err := c.cc.Invoke(ctx, AgentPools_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentPoolsClient) Delete(ctx context.Context, in *api.DeleteRequest, opts ...grpc.CallOption) (*api.DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(api.DeleteResponse)
	err := c.cc.Invoke(ctx, AgentPools_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentPoolsServer is the server API for AgentPools service.
// All implementations must embed UnimplementedAgentPoolsServer
// for forward compatibility.
type AgentPoolsServer interface {
	CreateOrUpdate(context.Context, *api.CreateOrUpdateRequest) (*api.CreateOrUpdateResponse, error)
	List(context.Context, *api.ListRequest) (*api.ListResponse, error)
	Get(context.Context, *api.GetRequest) (*api.GetResponse, error)
	Delete(context.Context, *api.DeleteRequest) (*api.DeleteResponse, error)
	mustEmbedUnimplementedAgentPoolsServer()
}

// UnimplementedAgentPoolsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentPoolsServer struct{}

func (UnimplementedAgentPoolsServer) CreateOrUpdate(context.Context, *api.CreateOrUpdateRequest) (*api.CreateOrUpdateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateOrUpdate not implemented")
}
func (UnimplementedAgentPoolsServer) List(context.Context, *api.ListRequest) (*api.ListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedAgentPoolsServer) Get(context.Context, *api.GetRequest) (*api.GetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedAgentPoolsServer) Delete(context.Context, *api.DeleteRequest) (*api.DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedAgentPoolsServer) mustEmbedUnimplementedAgentPoolsServer() {}
func (UnimplementedAgentPoolsServer) testEmbeddedByValue()                    {}

// UnsafeAgentPoolsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentPoolsServer will
// result in compilation errors.
type UnsafeAgentPoolsServer interface {
	mustEmbedUnimplementedAgentPoolsServer()
}

func RegisterAgentPoolsServer(s grpc.ServiceRegistrar, srv AgentPoolsServer) {
	// If the following call panics, it indicates UnimplementedAgentPoolsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentPools_ServiceDesc, srv)
}

func _AgentPools_CreateOrUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(api.CreateOrUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentPoolsServer).CreateOrUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentPools_CreateOrUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentPoolsServer).CreateOrUpdate(ctx, req.(*api.CreateOrUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentPools_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(api.ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentPoolsServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentPools_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentPoolsServer).List(ctx, req.(*api.ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentPools_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(api.GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentPoolsServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentPools_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentPoolsServer).Get(ctx, req.(*api.GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentPools_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(api.DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentPoolsServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentPools_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentPoolsServer).Delete(ctx, req.(*api.DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentPools_ServiceDesc is the grpc.ServiceDesc for AgentPools service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentPools_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agentpools.AgentPools",
	HandlerType: (*AgentPoolsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrUpdate",
			Handler:    _AgentPools_CreateOrUpdate_Handler,
		},
		{
			MethodName: "List",
			Handler:    _AgentPools_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _AgentPools_Get_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _AgentPools_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "flex-plugin/pkg/services/agentpools/api/agentpools.proto",
}
