// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: flex-plugin/pkg/services/agentpools/api/instances.proto

package api

import (
	api "github.com/Azure/aks-flex/flex-plugin/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InstanceRestartRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *InstanceRestartRequest) Reset() {
	*x = InstanceRestartRequest{}
	mi := &file_flex_plugin_pkg_services_agentpools_api_instances_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceRestartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceRestartRequest) ProtoMessage() {}

func (x *InstanceRestartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flex_plugin_pkg_services_agentpools_api_instances_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *InstanceRestartRequest) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *InstanceRestartRequest) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *InstanceRestartRequest) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *InstanceRestartRequest) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

type InstanceRestartRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id *string
}

func (b0 InstanceRestartRequest_builder) Build() *InstanceRestartRequest {
	m0 := &InstanceRestartRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Id = b.Id
	}
	return m0
}

type InstanceRestartResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstanceRestartResponse) Reset() {
	*x = InstanceRestartResponse{}
	mi := &file_flex_plugin_pkg_services_agentpools_api_instances_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceRestartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceRestartResponse) ProtoMessage() {}

func (x *InstanceRestartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flex_plugin_pkg_services_agentpools_api_instances_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type InstanceRestartResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 InstanceRestartResponse_builder) Build() *InstanceRestartResponse {
	m0 := &InstanceRestartResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_flex_plugin_pkg_services_agentpools_api_instances_proto protoreflect.FileDescriptor

const file_flex_plugin_pkg_services_agentpools_api_instances_proto_rawDesc = "" +
	"\n" +
	"7flex-plugin/pkg/services/agentpools/api/instances.proto\x12\n" +
	"agentpools\x1a\x19flex-plugin/api/api.proto\"(\n" +
	"\x16InstanceRestartRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x19\n" +
	"\x17InstanceRestartResponse2\xbe\x02\n" +
	"\tInstances\x12K\n" +
	"\x0eCreateOrUpdate\x12\x1a.api.CreateOrUpdateRequest\x1a\x1b.api.CreateOrUpdateResponse\"\x00\x12-\n" +
	"\x04List\x12\x10.api.ListRequest\x1a\x11.api.ListResponse\"\x00\x12*\n" +
	"\x03Get\x12\x0f.api.GetRequest\x1a\x10.api.GetResponse\"\x00\x123\n" +
	"\x06Delete\x12\x12.api.DeleteRequest\x1a\x13.api.DeleteResponse\"\x00\x12T\n" +
	"\aRestart\x12\".agentpools.InstanceRestartRequest\x1a#.agentpools.InstanceRestartResponse\"\x00BCZAgithub.com/Azure/aks-flex/flex-plugin/pkg/services/agentpools/apib\beditionsp\xe9\a"

var file_flex_plugin_pkg_services_agentpools_api_instances_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_flex_plugin_pkg_services_agentpools_api_instances_proto_goTypes = []any{
	(*InstanceRestartRequest)(nil),     // 0: agentpools.InstanceRestartRequest
	(*InstanceRestartResponse)(nil),    // 1: agentpools.InstanceRestartResponse
	(*api.CreateOrUpdateRequest)(nil),  // 2: api.CreateOrUpdateRequest
	(*api.ListRequest)(nil),            // 3: api.ListRequest
	(*api.GetRequest)(nil),             // 4: api.GetRequest
	(*api.DeleteRequest)(nil),          // 5: api.DeleteRequest
	(*api.CreateOrUpdateResponse)(nil), // 6: api.CreateOrUpdateResponse
	(*api.ListResponse)(nil),           // 7: api.ListResponse
	(*api.GetResponse)(nil),            // 8: api.GetResponse
	(*api.DeleteResponse)(nil),         // 9: api.DeleteResponse
}
var file_flex_plugin_pkg_services_agentpools_api_instances_proto_depIdxs = []int32{
	2, // 0: agentpools.Instances.CreateOrUpdate:input_type -> api.CreateOrUpdateRequest
	3, // 1: agentpools.Instances.List:input_type -> api.ListRequest
	4, // 2: agentpools.Instances.Get:input_type -> api.GetRequest
	5, // 3: agentpools.Instances.Delete:input_type -> api.DeleteRequest
	0, // 4: agentpools.Instances.Restart:input_type -> agentpools.InstanceRestartRequest
	6, // 5: agentpools.Instances.CreateOrUpdate:output_type -> api.CreateOrUpdateResponse
	7, // 6: agentpools.Instances.List:output_type -> api.ListResponse
	8, // 7: agentpools.Instances.Get:output_type -> api.GetResponse
	9, // 8: agentpools.Instances.Delete:output_type -> api.DeleteResponse
	1, // 9: agentpools.Instances.Restart:output_type -> agentpools.InstanceRestartResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_flex_plugin_pkg_services_agentpools_api_instances_proto_init() }
func file_flex_plugin_pkg_services_agentpools_api_instances_proto_init() {
	if File_flex_plugin_pkg_services_agentpools_api_instances_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_flex_plugin_pkg_services_agentpools_api_instances_proto_rawDesc), len(file_flex_plugin_pkg_services_agentpools_api_instances_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_flex_plugin_pkg_services_agentpools_api_instances_proto_goTypes,
		DependencyIndexes: file_flex_plugin_pkg_services_agentpools_api_instances_proto_depIdxs,
		MessageInfos:      file_flex_plugin_pkg_services_agentpools_api_instances_proto_msgTypes,
	}.Build()
	File_flex_plugin_pkg_services_agentpools_api_instances_proto = out.File
	file_flex_plugin_pkg_services_agentpools_api_instances_proto_goTypes = nil
	file_flex_plugin_pkg_services_agentpools_api_instances_proto_depIdxs = nil
}
