// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: plugin/pkg/services/agentpools/aws/ubuntu2404instance/agentpools.proto

package ubuntu2404instance

import (
	api "github.com/Azure/aks-flex/plugin/api"
	kubeadm "github.com/Azure/aks-flex/plugin/pkg/services/agentpools/api/features/kubeadm"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentPool struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Metadata *api.Metadata          `protobuf:"bytes,1,opt,name=metadata"`
	xxx_hidden_Spec     *AgentPoolSpec         `protobuf:"bytes,2,opt,name=spec"`
	xxx_hidden_Status   *AgentPoolStatus       `protobuf:"bytes,3,opt,name=status"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AgentPool) Reset() {
	*x = AgentPool{}
	mi := &file_plugin_pkg_services_agentpools_aws_ubuntu2404instance_agentpools_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentPool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentPool) ProtoMessage() {}

func (x *AgentPool) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pkg_services_agentpools_aws_ubuntu2404instance_agentpools_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AgentPool) GetMetadata() *api.Metadata {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return nil
}

func (x *AgentPool) GetSpec() *AgentPoolSpec {
	if x != nil {
		return x.xxx_hidden_Spec
	}
	return nil
}

func (x *AgentPool) GetStatus() *AgentPoolStatus {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return nil
}

func (x *AgentPool) SetMetadata(v *api.Metadata) {
	x.xxx_hidden_Metadata = v
}

func (x *AgentPool) SetSpec(v *AgentPoolSpec) {
	x.xxx_hidden_Spec = v
}

func (x *AgentPool) SetStatus(v *AgentPoolStatus) {
	x.xxx_hidden_Status = v
}

func (x *AgentPool) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Metadata != nil
}

func (x *AgentPool) HasSpec() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Spec != nil
}

func (x *AgentPool) HasStatus() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Status != nil
}

func (x *AgentPool) ClearMetadata() {
	x.xxx_hidden_Metadata = nil
}

func (x *AgentPool) ClearSpec() {
	x.xxx_hidden_Spec = nil
}

func (x *AgentPool) ClearStatus() {
	x.xxx_hidden_Status = nil
}

type AgentPool_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Metadata *api.Metadata
	Spec     *AgentPoolSpec
	Status   *AgentPoolStatus
}

func (b0 AgentPool_builder) Build() *AgentPool {
	m0 := &AgentPool{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Metadata = b.Metadata
	x.xxx_hidden_Spec = b.Spec
	x.xxx_hidden_Status = b.Status
	return m0
}

type AgentPoolSpec struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Region        *string                `protobuf:"bytes,1,opt,name=region"`
	xxx_hidden_Subnet        *string                `protobuf:"bytes,2,opt,name=subnet"`
	xxx_hidden_SecurityGroup *string                `protobuf:"bytes,3,opt,name=security_group,json=securityGroup"`
	xxx_hidden_Kubeadm       *kubeadm.Config        `protobuf:"bytes,4,opt,name=kubeadm"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *AgentPoolSpec) Reset() {
	*x = AgentPoolSpec{}
	mi := &file_plugin_pkg_services_agentpools_aws_ubuntu2404instance_agentpools_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentPoolSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentPoolSpec) ProtoMessage() {}

func (x *AgentPoolSpec) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pkg_services_agentpools_aws_ubuntu2404instance_agentpools_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AgentPoolSpec) GetRegion() string {
	if x != nil {
		if x.xxx_hidden_Region != nil {
			return *x.xxx_hidden_Region
		}
		return ""
	}
	return ""
}

func (x *AgentPoolSpec) GetSubnet() string {
	if x != nil {
		if x.xxx_hidden_Subnet != nil {
			return *x.xxx_hidden_Subnet
		}
		return ""
	}
	return ""
}

func (x *AgentPoolSpec) GetSecurityGroup() string {
	if x != nil {
		if x.xxx_hidden_SecurityGroup != nil {
			return *x.xxx_hidden_SecurityGroup
		}
		return ""
	}
	return ""
}

func (x *AgentPoolSpec) GetKubeadm() *kubeadm.Config {
	if x != nil {
		return x.xxx_hidden_Kubeadm
	}
	return nil
}

func (x *AgentPoolSpec) SetRegion(v string) {
	x.xxx_hidden_Region = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *AgentPoolSpec) SetSubnet(v string) {
	x.xxx_hidden_Subnet = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *AgentPoolSpec) SetSecurityGroup(v string) {
	x.xxx_hidden_SecurityGroup = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *AgentPoolSpec) SetKubeadm(v *kubeadm.Config) {
	x.xxx_hidden_Kubeadm = v
}

func (x *AgentPoolSpec) HasRegion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AgentPoolSpec) HasSubnet() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *AgentPoolSpec) HasSecurityGroup() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *AgentPoolSpec) HasKubeadm() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Kubeadm != nil
}

func (x *AgentPoolSpec) ClearRegion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Region = nil
}

func (x *AgentPoolSpec) ClearSubnet() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Subnet = nil
}

func (x *AgentPoolSpec) ClearSecurityGroup() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_SecurityGroup = nil
}

func (x *AgentPoolSpec) ClearKubeadm() {
	x.xxx_hidden_Kubeadm = nil
}

type AgentPoolSpec_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Region        *string
	Subnet        *string
	SecurityGroup *string
	Kubeadm       *kubeadm.Config
}

func (b0 AgentPoolSpec_builder) Build() *AgentPoolSpec {
	m0 := &AgentPoolSpec{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Region != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Region = b.Region
	}
	if b.Subnet != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_Subnet = b.Subnet
	}
	if b.SecurityGroup != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_SecurityGroup = b.SecurityGroup
	}
	x.xxx_hidden_Kubeadm = b.Kubeadm
	return m0
}

type AgentPoolStatus struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Instance    *string                `protobuf:"bytes,1,opt,name=instance"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AgentPoolStatus) Reset() {
	*x = AgentPoolStatus{}
	mi := &file_plugin_pkg_services_agentpools_aws_ubuntu2404instance_agentpools_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentPoolStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentPoolStatus) ProtoMessage() {}

func (x *AgentPoolStatus) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pkg_services_agentpools_aws_ubuntu2404instance_agentpools_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AgentPoolStatus) GetInstance() string {
	if x != nil {
		if x.xxx_hidden_Instance != nil {
			return *x.xxx_hidden_Instance
		}
		return ""
	}
	return ""
}

func (x *AgentPoolStatus) SetInstance(v string) {
	x.xxx_hidden_Instance = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *AgentPoolStatus) HasInstance() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AgentPoolStatus) ClearInstance() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Instance = nil
}

type AgentPoolStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Instance *string
}

func (b0 AgentPoolStatus_builder) Build() *AgentPoolStatus {
	m0 := &AgentPoolStatus{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Instance != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Instance = b.Instance
	}
	return m0
}

var File_plugin_pkg_services_agentpools_aws_ubuntu2404instance_agentpools_proto protoreflect.FileDescriptor

const file_plugin_pkg_services_agentpools_aws_ubuntu2404instance_agentpools_proto_rawDesc = "" +
	"\n" +
	"Fplugin/pkg/services/agentpools/aws/ubuntu2404instance/agentpools.proto\x12!agentpools.aws.ubuntu2404instance\x1a\x14plugin/api/api.proto\x1aAplugin/pkg/services/agentpools/api/features/kubeadm/kubeadm.proto\"\xc8\x01\n" +
	"\tAgentPool\x12)\n" +
	"\bmetadata\x18\x01 \x01(\v2\r.api.MetadataR\bmetadata\x12D\n" +
	"\x04spec\x18\x02 \x01(\v20.agentpools.aws.ubuntu2404instance.AgentPoolSpecR\x04spec\x12J\n" +
	"\x06status\x18\x03 \x01(\v22.agentpools.aws.ubuntu2404instance.AgentPoolStatusR\x06status\"\x91\x01\n" +
	"\rAgentPoolSpec\x12\x16\n" +
	"\x06region\x18\x01 \x01(\tR\x06region\x12\x16\n" +
	"\x06subnet\x18\x02 \x01(\tR\x06subnet\x12%\n" +
	"\x0esecurity_group\x18\x03 \x01(\tR\rsecurityGroup\x12)\n" +
	"\akubeadm\x18\x04 \x01(\v2\x0f.kubeadm.ConfigR\akubeadm\"-\n" +
	"\x0fAgentPoolStatus\x12\x1a\n" +
	"\binstance\x18\x01 \x01(\tR\binstanceBQZOgithub.com/Azure/aks-flex/plugin/pkg/services/agentpools/aws/ubuntu2404instanceb\beditionsp\xe9\a"

var file_plugin_pkg_services_agentpools_aws_ubuntu2404instance_agentpools_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_plugin_pkg_services_agentpools_aws_ubuntu2404instance_agentpools_proto_goTypes = []any{
	(*AgentPool)(nil),       // 0: agentpools.aws.ubuntu2404instance.AgentPool
	(*AgentPoolSpec)(nil),   // 1: agentpools.aws.ubuntu2404instance.AgentPoolSpec
	(*AgentPoolStatus)(nil), // 2: agentpools.aws.ubuntu2404instance.AgentPoolStatus
	(*api.Metadata)(nil),    // 3: api.Metadata
	(*kubeadm.Config)(nil),  // 4: kubeadm.Config
}
var file_plugin_pkg_services_agentpools_aws_ubuntu2404instance_agentpools_proto_depIdxs = []int32{
	3, // 0: agentpools.aws.ubuntu2404instance.AgentPool.metadata:type_name -> api.Metadata
	1, // 1: agentpools.aws.ubuntu2404instance.AgentPool.spec:type_name -> agentpools.aws.ubuntu2404instance.AgentPoolSpec
	2, // 2: agentpools.aws.ubuntu2404instance.AgentPool.status:type_name -> agentpools.aws.ubuntu2404instance.AgentPoolStatus
	4, // 3: agentpools.aws.ubuntu2404instance.AgentPoolSpec.kubeadm:type_name -> kubeadm.Config
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_plugin_pkg_services_agentpools_aws_ubuntu2404instance_agentpools_proto_init() }
func file_plugin_pkg_services_agentpools_aws_ubuntu2404instance_agentpools_proto_init() {
	if File_plugin_pkg_services_agentpools_aws_ubuntu2404instance_agentpools_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_pkg_services_agentpools_aws_ubuntu2404instance_agentpools_proto_rawDesc), len(file_plugin_pkg_services_agentpools_aws_ubuntu2404instance_agentpools_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_plugin_pkg_services_agentpools_aws_ubuntu2404instance_agentpools_proto_goTypes,
		DependencyIndexes: file_plugin_pkg_services_agentpools_aws_ubuntu2404instance_agentpools_proto_depIdxs,
		MessageInfos:      file_plugin_pkg_services_agentpools_aws_ubuntu2404instance_agentpools_proto_msgTypes,
	}.Build()
	File_plugin_pkg_services_agentpools_aws_ubuntu2404instance_agentpools_proto = out.File
	file_plugin_pkg_services_agentpools_aws_ubuntu2404instance_agentpools_proto_goTypes = nil
	file_plugin_pkg_services_agentpools_aws_ubuntu2404instance_agentpools_proto_depIdxs = nil
}
