{{- if and .Values.controller.nebiusCredentials.enabled .Values.controller.nebiusCredentials.credentialsJSON }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.controller.nebiusCredentials.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "karpenter.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.controller.nebiusCredentials.secretKey }}: {{ .Values.controller.nebiusCredentials.credentialsJSON | quote }}
{{- end }}
