// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: plugin/pkg/services/peerings/aws/ipsecvpn/ipsecvpn.proto

package ipsecvpn

import (
	api "github.com/Azure/aks-flex/plugin/api"
	ipsec "github.com/Azure/aks-flex/plugin/pkg/services/peerings/api/features/ipsec"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Peering struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Metadata *api.Metadata          `protobuf:"bytes,1,opt,name=metadata"`
	xxx_hidden_Spec     *PeeringSpec           `protobuf:"bytes,2,opt,name=spec"`
	xxx_hidden_Status   *PeeringStatus         `protobuf:"bytes,3,opt,name=status"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Peering) Reset() {
	*x = Peering{}
	mi := &file_flex_plugin_pkg_services_peerings_aws_ipsecvpn_ipsecvpn_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Peering) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Peering) ProtoMessage() {}

func (x *Peering) ProtoReflect() protoreflect.Message {
	mi := &file_flex_plugin_pkg_services_peerings_aws_ipsecvpn_ipsecvpn_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Peering) GetMetadata() *api.Metadata {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return nil
}

func (x *Peering) GetSpec() *PeeringSpec {
	if x != nil {
		return x.xxx_hidden_Spec
	}
	return nil
}

func (x *Peering) GetStatus() *PeeringStatus {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return nil
}

func (x *Peering) SetMetadata(v *api.Metadata) {
	x.xxx_hidden_Metadata = v
}

func (x *Peering) SetSpec(v *PeeringSpec) {
	x.xxx_hidden_Spec = v
}

func (x *Peering) SetStatus(v *PeeringStatus) {
	x.xxx_hidden_Status = v
}

func (x *Peering) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Metadata != nil
}

func (x *Peering) HasSpec() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Spec != nil
}

func (x *Peering) HasStatus() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Status != nil
}

func (x *Peering) ClearMetadata() {
	x.xxx_hidden_Metadata = nil
}

func (x *Peering) ClearSpec() {
	x.xxx_hidden_Spec = nil
}

func (x *Peering) ClearStatus() {
	x.xxx_hidden_Status = nil
}

type Peering_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Metadata *api.Metadata
	Spec     *PeeringSpec
	Status   *PeeringStatus
}

func (b0 Peering_builder) Build() *Peering {
	m0 := &Peering{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Metadata = b.Metadata
	x.xxx_hidden_Spec = b.Spec
	x.xxx_hidden_Status = b.Status
	return m0
}

type PeeringSpec struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Region      *string                `protobuf:"bytes,1,opt,name=region"`
	xxx_hidden_Vpc         *string                `protobuf:"bytes,2,opt,name=vpc"`
	xxx_hidden_RouteTable  *string                `protobuf:"bytes,3,opt,name=route_table,json=routeTable"`
	xxx_hidden_Ipsec       *ipsec.Config          `protobuf:"bytes,4,opt,name=ipsec"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PeeringSpec) Reset() {
	*x = PeeringSpec{}
	mi := &file_flex_plugin_pkg_services_peerings_aws_ipsecvpn_ipsecvpn_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeeringSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeeringSpec) ProtoMessage() {}

func (x *PeeringSpec) ProtoReflect() protoreflect.Message {
	mi := &file_flex_plugin_pkg_services_peerings_aws_ipsecvpn_ipsecvpn_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PeeringSpec) GetRegion() string {
	if x != nil {
		if x.xxx_hidden_Region != nil {
			return *x.xxx_hidden_Region
		}
		return ""
	}
	return ""
}

func (x *PeeringSpec) GetVpc() string {
	if x != nil {
		if x.xxx_hidden_Vpc != nil {
			return *x.xxx_hidden_Vpc
		}
		return ""
	}
	return ""
}

func (x *PeeringSpec) GetRouteTable() string {
	if x != nil {
		if x.xxx_hidden_RouteTable != nil {
			return *x.xxx_hidden_RouteTable
		}
		return ""
	}
	return ""
}

func (x *PeeringSpec) GetIpsec() *ipsec.Config {
	if x != nil {
		return x.xxx_hidden_Ipsec
	}
	return nil
}

func (x *PeeringSpec) SetRegion(v string) {
	x.xxx_hidden_Region = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *PeeringSpec) SetVpc(v string) {
	x.xxx_hidden_Vpc = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *PeeringSpec) SetRouteTable(v string) {
	x.xxx_hidden_RouteTable = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *PeeringSpec) SetIpsec(v *ipsec.Config) {
	x.xxx_hidden_Ipsec = v
}

func (x *PeeringSpec) HasRegion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *PeeringSpec) HasVpc() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *PeeringSpec) HasRouteTable() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *PeeringSpec) HasIpsec() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ipsec != nil
}

func (x *PeeringSpec) ClearRegion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Region = nil
}

func (x *PeeringSpec) ClearVpc() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Vpc = nil
}

func (x *PeeringSpec) ClearRouteTable() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_RouteTable = nil
}

func (x *PeeringSpec) ClearIpsec() {
	x.xxx_hidden_Ipsec = nil
}

type PeeringSpec_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Region     *string
	Vpc        *string
	RouteTable *string
	Ipsec      *ipsec.Config
}

func (b0 PeeringSpec_builder) Build() *PeeringSpec {
	m0 := &PeeringSpec{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Region != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Region = b.Region
	}
	if b.Vpc != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_Vpc = b.Vpc
	}
	if b.RouteTable != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_RouteTable = b.RouteTable
	}
	x.xxx_hidden_Ipsec = b.Ipsec
	return m0
}

type PeeringStatus struct {
	state                         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_VpnConnection      *string                `protobuf:"bytes,1,opt,name=vpn_connection,json=vpnConnection"`
	xxx_hidden_OutsideIpAddresses []string               `protobuf:"bytes,2,rep,name=outside_ip_addresses,json=outsideIpAddresses"`
	XXX_raceDetectHookData        protoimpl.RaceDetectHookData
	XXX_presence                  [1]uint32
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *PeeringStatus) Reset() {
	*x = PeeringStatus{}
	mi := &file_flex_plugin_pkg_services_peerings_aws_ipsecvpn_ipsecvpn_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeeringStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeeringStatus) ProtoMessage() {}

func (x *PeeringStatus) ProtoReflect() protoreflect.Message {
	mi := &file_flex_plugin_pkg_services_peerings_aws_ipsecvpn_ipsecvpn_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PeeringStatus) GetVpnConnection() string {
	if x != nil {
		if x.xxx_hidden_VpnConnection != nil {
			return *x.xxx_hidden_VpnConnection
		}
		return ""
	}
	return ""
}

func (x *PeeringStatus) GetOutsideIpAddresses() []string {
	if x != nil {
		return x.xxx_hidden_OutsideIpAddresses
	}
	return nil
}

func (x *PeeringStatus) SetVpnConnection(v string) {
	x.xxx_hidden_VpnConnection = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *PeeringStatus) SetOutsideIpAddresses(v []string) {
	x.xxx_hidden_OutsideIpAddresses = v
}

func (x *PeeringStatus) HasVpnConnection() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *PeeringStatus) ClearVpnConnection() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_VpnConnection = nil
}

type PeeringStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	VpnConnection      *string
	OutsideIpAddresses []string
}

func (b0 PeeringStatus_builder) Build() *PeeringStatus {
	m0 := &PeeringStatus{}
	b, x := &b0, m0
	_, _ = b, x
	if b.VpnConnection != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_VpnConnection = b.VpnConnection
	}
	x.xxx_hidden_OutsideIpAddresses = b.OutsideIpAddresses
	return m0
}

var File_flex_plugin_pkg_services_peerings_aws_ipsecvpn_ipsecvpn_proto protoreflect.FileDescriptor

const file_flex_plugin_pkg_services_peerings_aws_ipsecvpn_ipsecvpn_proto_rawDesc = "" +
	"\n" +
	"=plugin/pkg/services/peerings/aws/ipsecvpn/ipsecvpn.proto\x12\bipsecvpn\x1a\x19plugin/api/api.proto\x1a@plugin/pkg/services/peerings/api/features/ipsec/ipsec.proto\"\x90\x01\n" +
	"\aPeering\x12)\n" +
	"\bmetadata\x18\x01 \x01(\v2\r.api.MetadataR\bmetadata\x12)\n" +
	"\x04spec\x18\x02 \x01(\v2\x15.ipsecvpn.PeeringSpecR\x04spec\x12/\n" +
	"\x06status\x18\x03 \x01(\v2\x17.ipsecvpn.PeeringStatusR\x06status\"}\n" +
	"\vPeeringSpec\x12\x16\n" +
	"\x06region\x18\x01 \x01(\tR\x06region\x12\x10\n" +
	"\x03vpc\x18\x02 \x01(\tR\x03vpc\x12\x1f\n" +
	"\vroute_table\x18\x03 \x01(\tR\n" +
	"routeTable\x12#\n" +
	"\x05ipsec\x18\x04 \x01(\v2\r.ipsec.ConfigR\x05ipsec\"h\n" +
	"\rPeeringStatus\x12%\n" +
	"\x0evpn_connection\x18\x01 \x01(\tR\rvpnConnection\x120\n" +
	"\x14outside_ip_addresses\x18\x02 \x03(\tR\x12outsideIpAddressesBJZHgithub.com/Azure/aks-flex/plugin/pkg/services/peerings/aws/ipsecvpnb\beditionsp\xe9\a"

var file_flex_plugin_pkg_services_peerings_aws_ipsecvpn_ipsecvpn_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_flex_plugin_pkg_services_peerings_aws_ipsecvpn_ipsecvpn_proto_goTypes = []any{
	(*Peering)(nil),       // 0: ipsecvpn.Peering
	(*PeeringSpec)(nil),   // 1: ipsecvpn.PeeringSpec
	(*PeeringStatus)(nil), // 2: ipsecvpn.PeeringStatus
	(*api.Metadata)(nil),  // 3: api.Metadata
	(*ipsec.Config)(nil),  // 4: ipsec.Config
}
var file_flex_plugin_pkg_services_peerings_aws_ipsecvpn_ipsecvpn_proto_depIdxs = []int32{
	3, // 0: ipsecvpn.Peering.metadata:type_name -> api.Metadata
	1, // 1: ipsecvpn.Peering.spec:type_name -> ipsecvpn.PeeringSpec
	2, // 2: ipsecvpn.Peering.status:type_name -> ipsecvpn.PeeringStatus
	4, // 3: ipsecvpn.PeeringSpec.ipsec:type_name -> ipsec.Config
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_flex_plugin_pkg_services_peerings_aws_ipsecvpn_ipsecvpn_proto_init() }
func file_flex_plugin_pkg_services_peerings_aws_ipsecvpn_ipsecvpn_proto_init() {
	if File_flex_plugin_pkg_services_peerings_aws_ipsecvpn_ipsecvpn_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_flex_plugin_pkg_services_peerings_aws_ipsecvpn_ipsecvpn_proto_rawDesc), len(file_flex_plugin_pkg_services_peerings_aws_ipsecvpn_ipsecvpn_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_flex_plugin_pkg_services_peerings_aws_ipsecvpn_ipsecvpn_proto_goTypes,
		DependencyIndexes: file_flex_plugin_pkg_services_peerings_aws_ipsecvpn_ipsecvpn_proto_depIdxs,
		MessageInfos:      file_flex_plugin_pkg_services_peerings_aws_ipsecvpn_ipsecvpn_proto_msgTypes,
	}.Build()
	File_flex_plugin_pkg_services_peerings_aws_ipsecvpn_ipsecvpn_proto = out.File
	file_flex_plugin_pkg_services_peerings_aws_ipsecvpn_ipsecvpn_proto_goTypes = nil
	file_flex_plugin_pkg_services_peerings_aws_ipsecvpn_ipsecvpn_proto_depIdxs = nil
}
