apiVersion: infrastructure.flex-capi.aks.azure.com/v1beta2
kind: NebiusMachineTemplate
metadata:
  labels:
    app.kubernetes.io/name: cluster-api-provider-flex
    app.kubernetes.io/managed-by: kustomize
  name: nebiusmachinetemplate-sample
spec:
  # TODO(user): Add fields here
