// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: plugin/pkg/services/agentpools/api/features/gpu/gpu.proto

package gpu

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Config struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_plugin_pkg_services_agentpools_api_features_gpu_gpu_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pkg_services_agentpools_api_features_gpu_gpu_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type Config_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 Config_builder) Build() *Config {
	m0 := &Config{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_plugin_pkg_services_agentpools_api_features_gpu_gpu_proto protoreflect.FileDescriptor

const file_plugin_pkg_services_agentpools_api_features_gpu_gpu_proto_rawDesc = "" +
	"\n" +
	"9plugin/pkg/services/agentpools/api/features/gpu/gpu.proto\x12\x03gpu\"\b\n" +
	"\x06ConfigBKZIgithub.com/Azure/aks-flex/plugin/pkg/services/agentpools/api/features/gpub\beditionsp\xe9\a"

var file_plugin_pkg_services_agentpools_api_features_gpu_gpu_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_plugin_pkg_services_agentpools_api_features_gpu_gpu_proto_goTypes = []any{
	(*Config)(nil), // 0: gpu.Config
}
var file_plugin_pkg_services_agentpools_api_features_gpu_gpu_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_plugin_pkg_services_agentpools_api_features_gpu_gpu_proto_init() }
func file_plugin_pkg_services_agentpools_api_features_gpu_gpu_proto_init() {
	if File_plugin_pkg_services_agentpools_api_features_gpu_gpu_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_pkg_services_agentpools_api_features_gpu_gpu_proto_rawDesc), len(file_plugin_pkg_services_agentpools_api_features_gpu_gpu_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_plugin_pkg_services_agentpools_api_features_gpu_gpu_proto_goTypes,
		DependencyIndexes: file_plugin_pkg_services_agentpools_api_features_gpu_gpu_proto_depIdxs,
		MessageInfos:      file_plugin_pkg_services_agentpools_api_features_gpu_gpu_proto_msgTypes,
	}.Build()
	File_plugin_pkg_services_agentpools_api_features_gpu_gpu_proto = out.File
	file_plugin_pkg_services_agentpools_api_features_gpu_gpu_proto_goTypes = nil
	file_plugin_pkg_services_agentpools_api_features_gpu_gpu_proto_depIdxs = nil
}
