// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: flex-plugin/pkg/services/networks/api/features/vnet/vnet.proto

package vnet

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Config struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_CidrBlock   *string                `protobuf:"bytes,1,opt,name=cidr_block,json=cidrBlock"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_flex_plugin_pkg_services_networks_api_features_vnet_vnet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_flex_plugin_pkg_services_networks_api_features_vnet_vnet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Config) GetCidrBlock() string {
	if x != nil {
		if x.xxx_hidden_CidrBlock != nil {
			return *x.xxx_hidden_CidrBlock
		}
		return ""
	}
	return ""
}

func (x *Config) SetCidrBlock(v string) {
	x.xxx_hidden_CidrBlock = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *Config) HasCidrBlock() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Config) ClearCidrBlock() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_CidrBlock = nil
}

type Config_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	CidrBlock *string
}

func (b0 Config_builder) Build() *Config {
	m0 := &Config{}
	b, x := &b0, m0
	_, _ = b, x
	if b.CidrBlock != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_CidrBlock = b.CidrBlock
	}
	return m0
}

var File_flex_plugin_pkg_services_networks_api_features_vnet_vnet_proto protoreflect.FileDescriptor

const file_flex_plugin_pkg_services_networks_api_features_vnet_vnet_proto_rawDesc = "" +
	"\n" +
	">flex-plugin/pkg/services/networks/api/features/vnet/vnet.proto\x12\x04vnet\"'\n" +
	"\x06Config\x12\x1d\n" +
	"\n" +
	"cidr_block\x18\x01 \x01(\tR\tcidrBlockBOZMgithub.com/Azure/aks-flex/flex-plugin/pkg/services/networks/api/features/vnetb\beditionsp\xe9\a"

var file_flex_plugin_pkg_services_networks_api_features_vnet_vnet_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_flex_plugin_pkg_services_networks_api_features_vnet_vnet_proto_goTypes = []any{
	(*Config)(nil), // 0: vnet.Config
}
var file_flex_plugin_pkg_services_networks_api_features_vnet_vnet_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_flex_plugin_pkg_services_networks_api_features_vnet_vnet_proto_init() }
func file_flex_plugin_pkg_services_networks_api_features_vnet_vnet_proto_init() {
	if File_flex_plugin_pkg_services_networks_api_features_vnet_vnet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_flex_plugin_pkg_services_networks_api_features_vnet_vnet_proto_rawDesc), len(file_flex_plugin_pkg_services_networks_api_features_vnet_vnet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_flex_plugin_pkg_services_networks_api_features_vnet_vnet_proto_goTypes,
		DependencyIndexes: file_flex_plugin_pkg_services_networks_api_features_vnet_vnet_proto_depIdxs,
		MessageInfos:      file_flex_plugin_pkg_services_networks_api_features_vnet_vnet_proto_msgTypes,
	}.Build()
	File_flex_plugin_pkg_services_networks_api_features_vnet_vnet_proto = out.File
	file_flex_plugin_pkg_services_networks_api_features_vnet_vnet_proto_goTypes = nil
	file_flex_plugin_pkg_services_networks_api_features_vnet_vnet_proto_depIdxs = nil
}
