---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - infrastructure.flex-capi.aks.azure.com
  resources:
  - nebiusmachines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infrastructure.flex-capi.aks.azure.com
  resources:
  - nebiusmachines/finalizers
  verbs:
  - update
- apiGroups:
  - infrastructure.flex-capi.aks.azure.com
  resources:
  - nebiusmachines/status
  verbs:
  - get
  - patch
  - update
