apiVersion: flex.aks.azure.com/v1alpha1
kind: NebiusNodeClass
metadata:
  name: nebius
spec:
  projectID: "<your-nebius-project-id>"
  region: "<your-nebius-region>"
  subnetID: "<your-nebius-subnet-id>"
  osDiskSizeGB: 128
  wireguardPeerCIDR: "100.96.1.0/24"
