//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/awslabs/operatorpkg/status"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NebiusNodeClass) DeepCopyInto(out *NebiusNodeClass) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NebiusNodeClass.
func (in *NebiusNodeClass) DeepCopy() *NebiusNodeClass {
	if in == nil {
		return nil
	}
	out := new(NebiusNodeClass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NebiusNodeClass) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NebiusNodeClassList) DeepCopyInto(out *NebiusNodeClassList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NebiusNodeClass, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NebiusNodeClassList.
func (in *NebiusNodeClassList) DeepCopy() *NebiusNodeClassList {
	if in == nil {
		return nil
	}
	out := new(NebiusNodeClassList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NebiusNodeClassList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NebiusNodeClassSpec) DeepCopyInto(out *NebiusNodeClassSpec) {
	*out = *in
	if in.OSDiskSizeGB != nil {
		in, out := &in.OSDiskSizeGB, &out.OSDiskSizeGB
		*out = new(int32)
		**out = **in
	}
	if in.OSDiskImageFamily != nil {
		in, out := &in.OSDiskImageFamily, &out.OSDiskImageFamily
		*out = new(string)
		**out = **in
	}
	if in.AllocateNodePublicIP != nil {
		in, out := &in.AllocateNodePublicIP, &out.AllocateNodePublicIP
		*out = new(bool)
		**out = **in
	}
	if in.WireguardPeerCIDR != nil {
		in, out := &in.WireguardPeerCIDR, &out.WireguardPeerCIDR
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NebiusNodeClassSpec.
func (in *NebiusNodeClassSpec) DeepCopy() *NebiusNodeClassSpec {
	if in == nil {
		return nil
	}
	out := new(NebiusNodeClassSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NebiusNodeClassStatus) DeepCopyInto(out *NebiusNodeClassStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]status.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NebiusNodeClassStatus.
func (in *NebiusNodeClassStatus) DeepCopy() *NebiusNodeClassStatus {
	if in == nil {
		return nil
	}
	out := new(NebiusNodeClassStatus)
	in.DeepCopyInto(out)
	return out
}
