// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: plugin/pkg/services/agentpools/api/agentpools.proto

package api

import (
	api "github.com/Azure/aks-flex/plugin/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_flex_plugin_pkg_services_agentpools_api_agentpools_proto protoreflect.FileDescriptor

const file_flex_plugin_pkg_services_agentpools_api_agentpools_proto_rawDesc = "" +
	"\n" +
	"8plugin/pkg/services/agentpools/api/agentpools.proto\x12\n" +
	"agentpools\x1a\x19plugin/api/api.proto2\xe9\x01\n" +
	"\n" +
	"AgentPools\x12K\n" +
	"\x0eCreateOrUpdate\x12\x1a.api.CreateOrUpdateRequest\x1a\x1b.api.CreateOrUpdateResponse\"\x00\x12-\n" +
	"\x04List\x12\x10.api.ListRequest\x1a\x11.api.ListResponse\"\x00\x12*\n" +
	"\x03Get\x12\x0f.api.GetRequest\x1a\x10.api.GetResponse\"\x00\x123\n" +
	"\x06Delete\x12\x12.api.DeleteRequest\x1a\x13.api.DeleteResponse\"\x00BCZAgithub.com/Azure/aks-flex/plugin/pkg/services/agentpools/apib\beditionsp\xe9\a"

var file_flex_plugin_pkg_services_agentpools_api_agentpools_proto_goTypes = []any{
	(*api.CreateOrUpdateRequest)(nil),  // 0: api.CreateOrUpdateRequest
	(*api.ListRequest)(nil),            // 1: api.ListRequest
	(*api.GetRequest)(nil),             // 2: api.GetRequest
	(*api.DeleteRequest)(nil),          // 3: api.DeleteRequest
	(*api.CreateOrUpdateResponse)(nil), // 4: api.CreateOrUpdateResponse
	(*api.ListResponse)(nil),           // 5: api.ListResponse
	(*api.GetResponse)(nil),            // 6: api.GetResponse
	(*api.DeleteResponse)(nil),         // 7: api.DeleteResponse
}
var file_flex_plugin_pkg_services_agentpools_api_agentpools_proto_depIdxs = []int32{
	0, // 0: agentpools.AgentPools.CreateOrUpdate:input_type -> api.CreateOrUpdateRequest
	1, // 1: agentpools.AgentPools.List:input_type -> api.ListRequest
	2, // 2: agentpools.AgentPools.Get:input_type -> api.GetRequest
	3, // 3: agentpools.AgentPools.Delete:input_type -> api.DeleteRequest
	4, // 4: agentpools.AgentPools.CreateOrUpdate:output_type -> api.CreateOrUpdateResponse
	5, // 5: agentpools.AgentPools.List:output_type -> api.ListResponse
	6, // 6: agentpools.AgentPools.Get:output_type -> api.GetResponse
	7, // 7: agentpools.AgentPools.Delete:output_type -> api.DeleteResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_flex_plugin_pkg_services_agentpools_api_agentpools_proto_init() }
func file_flex_plugin_pkg_services_agentpools_api_agentpools_proto_init() {
	if File_flex_plugin_pkg_services_agentpools_api_agentpools_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_flex_plugin_pkg_services_agentpools_api_agentpools_proto_rawDesc), len(file_flex_plugin_pkg_services_agentpools_api_agentpools_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_flex_plugin_pkg_services_agentpools_api_agentpools_proto_goTypes,
		DependencyIndexes: file_flex_plugin_pkg_services_agentpools_api_agentpools_proto_depIdxs,
	}.Build()
	File_flex_plugin_pkg_services_agentpools_api_agentpools_proto = out.File
	file_flex_plugin_pkg_services_agentpools_api_agentpools_proto_goTypes = nil
	file_flex_plugin_pkg_services_agentpools_api_agentpools_proto_depIdxs = nil
}
