// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: plugin/pkg/services/networks/nebius/vpc/vpc.proto

package vpc

import (
	api "github.com/Azure/aks-flex/plugin/api"
	vnet "github.com/Azure/aks-flex/plugin/pkg/services/networks/api/features/vnet"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Network struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Metadata *api.Metadata          `protobuf:"bytes,1,opt,name=metadata"`
	xxx_hidden_Spec     *NetworkSpec           `protobuf:"bytes,2,opt,name=spec"`
	xxx_hidden_Status   *NetworkStatus         `protobuf:"bytes,3,opt,name=status"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Network) Reset() {
	*x = Network{}
	mi := &file_plugin_pkg_services_networks_nebius_vpc_vpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Network) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Network) ProtoMessage() {}

func (x *Network) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pkg_services_networks_nebius_vpc_vpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Network) GetMetadata() *api.Metadata {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return nil
}

func (x *Network) GetSpec() *NetworkSpec {
	if x != nil {
		return x.xxx_hidden_Spec
	}
	return nil
}

func (x *Network) GetStatus() *NetworkStatus {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return nil
}

func (x *Network) SetMetadata(v *api.Metadata) {
	x.xxx_hidden_Metadata = v
}

func (x *Network) SetSpec(v *NetworkSpec) {
	x.xxx_hidden_Spec = v
}

func (x *Network) SetStatus(v *NetworkStatus) {
	x.xxx_hidden_Status = v
}

func (x *Network) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Metadata != nil
}

func (x *Network) HasSpec() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Spec != nil
}

func (x *Network) HasStatus() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Status != nil
}

func (x *Network) ClearMetadata() {
	x.xxx_hidden_Metadata = nil
}

func (x *Network) ClearSpec() {
	x.xxx_hidden_Spec = nil
}

func (x *Network) ClearStatus() {
	x.xxx_hidden_Status = nil
}

type Network_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Metadata *api.Metadata
	Spec     *NetworkSpec
	Status   *NetworkStatus
}

func (b0 Network_builder) Build() *Network {
	m0 := &Network{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Metadata = b.Metadata
	x.xxx_hidden_Spec = b.Spec
	x.xxx_hidden_Status = b.Status
	return m0
}

type NetworkSpec struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ProjectId   *string                `protobuf:"bytes,1,opt,name=project_id,json=projectId"`
	xxx_hidden_Region      *string                `protobuf:"bytes,2,opt,name=region"`
	xxx_hidden_Vnet        *vnet.Config           `protobuf:"bytes,3,opt,name=vnet"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *NetworkSpec) Reset() {
	*x = NetworkSpec{}
	mi := &file_plugin_pkg_services_networks_nebius_vpc_vpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkSpec) ProtoMessage() {}

func (x *NetworkSpec) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pkg_services_networks_nebius_vpc_vpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *NetworkSpec) GetProjectId() string {
	if x != nil {
		if x.xxx_hidden_ProjectId != nil {
			return *x.xxx_hidden_ProjectId
		}
		return ""
	}
	return ""
}

func (x *NetworkSpec) GetRegion() string {
	if x != nil {
		if x.xxx_hidden_Region != nil {
			return *x.xxx_hidden_Region
		}
		return ""
	}
	return ""
}

func (x *NetworkSpec) GetVnet() *vnet.Config {
	if x != nil {
		return x.xxx_hidden_Vnet
	}
	return nil
}

func (x *NetworkSpec) SetProjectId(v string) {
	x.xxx_hidden_ProjectId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *NetworkSpec) SetRegion(v string) {
	x.xxx_hidden_Region = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *NetworkSpec) SetVnet(v *vnet.Config) {
	x.xxx_hidden_Vnet = v
}

func (x *NetworkSpec) HasProjectId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *NetworkSpec) HasRegion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *NetworkSpec) HasVnet() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Vnet != nil
}

func (x *NetworkSpec) ClearProjectId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_ProjectId = nil
}

func (x *NetworkSpec) ClearRegion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Region = nil
}

func (x *NetworkSpec) ClearVnet() {
	x.xxx_hidden_Vnet = nil
}

type NetworkSpec_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ProjectId *string
	Region    *string
	Vnet      *vnet.Config
}

func (b0 NetworkSpec_builder) Build() *NetworkSpec {
	m0 := &NetworkSpec{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ProjectId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_ProjectId = b.ProjectId
	}
	if b.Region != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Region = b.Region
	}
	x.xxx_hidden_Vnet = b.Vnet
	return m0
}

type NetworkStatus struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_PoolId      *string                `protobuf:"bytes,1,opt,name=pool_id,json=poolId"`
	xxx_hidden_VnetId      *string                `protobuf:"bytes,2,opt,name=vnet_id,json=vnetId"`
	xxx_hidden_SubnetId    *string                `protobuf:"bytes,3,opt,name=subnet_id,json=subnetId"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *NetworkStatus) Reset() {
	*x = NetworkStatus{}
	mi := &file_plugin_pkg_services_networks_nebius_vpc_vpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkStatus) ProtoMessage() {}

func (x *NetworkStatus) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pkg_services_networks_nebius_vpc_vpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *NetworkStatus) GetPoolId() string {
	if x != nil {
		if x.xxx_hidden_PoolId != nil {
			return *x.xxx_hidden_PoolId
		}
		return ""
	}
	return ""
}

func (x *NetworkStatus) GetVnetId() string {
	if x != nil {
		if x.xxx_hidden_VnetId != nil {
			return *x.xxx_hidden_VnetId
		}
		return ""
	}
	return ""
}

func (x *NetworkStatus) GetSubnetId() string {
	if x != nil {
		if x.xxx_hidden_SubnetId != nil {
			return *x.xxx_hidden_SubnetId
		}
		return ""
	}
	return ""
}

func (x *NetworkStatus) SetPoolId(v string) {
	x.xxx_hidden_PoolId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *NetworkStatus) SetVnetId(v string) {
	x.xxx_hidden_VnetId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *NetworkStatus) SetSubnetId(v string) {
	x.xxx_hidden_SubnetId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *NetworkStatus) HasPoolId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *NetworkStatus) HasVnetId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *NetworkStatus) HasSubnetId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *NetworkStatus) ClearPoolId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_PoolId = nil
}

func (x *NetworkStatus) ClearVnetId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_VnetId = nil
}

func (x *NetworkStatus) ClearSubnetId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_SubnetId = nil
}

type NetworkStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	PoolId   *string
	VnetId   *string
	SubnetId *string
}

func (b0 NetworkStatus_builder) Build() *NetworkStatus {
	m0 := &NetworkStatus{}
	b, x := &b0, m0
	_, _ = b, x
	if b.PoolId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_PoolId = b.PoolId
	}
	if b.VnetId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_VnetId = b.VnetId
	}
	if b.SubnetId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_SubnetId = b.SubnetId
	}
	return m0
}

var File_plugin_pkg_services_networks_nebius_vpc_vpc_proto protoreflect.FileDescriptor

const file_plugin_pkg_services_networks_nebius_vpc_vpc_proto_rawDesc = "" +
	"\n" +
	"1plugin/pkg/services/networks/nebius/vpc/vpc.proto\x12\x17networks.nebius.network\x1a\x14plugin/api/api.proto\x1a9plugin/pkg/services/networks/api/features/vnet/vnet.proto\"\xae\x01\n" +
	"\aNetwork\x12)\n" +
	"\bmetadata\x18\x01 \x01(\v2\r.api.MetadataR\bmetadata\x128\n" +
	"\x04spec\x18\x02 \x01(\v2$.networks.nebius.network.NetworkSpecR\x04spec\x12>\n" +
	"\x06status\x18\x03 \x01(\v2&.networks.nebius.network.NetworkStatusR\x06status\"f\n" +
	"\vNetworkSpec\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12 \n" +
	"\x04vnet\x18\x03 \x01(\v2\f.vnet.ConfigR\x04vnet\"^\n" +
	"\rNetworkStatus\x12\x17\n" +
	"\apool_id\x18\x01 \x01(\tR\x06poolId\x12\x17\n" +
	"\avnet_id\x18\x02 \x01(\tR\x06vnetId\x12\x1b\n" +
	"\tsubnet_id\x18\x03 \x01(\tR\bsubnetIdBCZAgithub.com/Azure/aks-flex/plugin/pkg/services/networks/nebius/vpcb\beditionsp\xe9\a"

var file_plugin_pkg_services_networks_nebius_vpc_vpc_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_plugin_pkg_services_networks_nebius_vpc_vpc_proto_goTypes = []any{
	(*Network)(nil),       // 0: networks.nebius.network.Network
	(*NetworkSpec)(nil),   // 1: networks.nebius.network.NetworkSpec
	(*NetworkStatus)(nil), // 2: networks.nebius.network.NetworkStatus
	(*api.Metadata)(nil),  // 3: api.Metadata
	(*vnet.Config)(nil),   // 4: vnet.Config
}
var file_plugin_pkg_services_networks_nebius_vpc_vpc_proto_depIdxs = []int32{
	3, // 0: networks.nebius.network.Network.metadata:type_name -> api.Metadata
	1, // 1: networks.nebius.network.Network.spec:type_name -> networks.nebius.network.NetworkSpec
	2, // 2: networks.nebius.network.Network.status:type_name -> networks.nebius.network.NetworkStatus
	4, // 3: networks.nebius.network.NetworkSpec.vnet:type_name -> vnet.Config
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_plugin_pkg_services_networks_nebius_vpc_vpc_proto_init() }
func file_plugin_pkg_services_networks_nebius_vpc_vpc_proto_init() {
	if File_plugin_pkg_services_networks_nebius_vpc_vpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_pkg_services_networks_nebius_vpc_vpc_proto_rawDesc), len(file_plugin_pkg_services_networks_nebius_vpc_vpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_plugin_pkg_services_networks_nebius_vpc_vpc_proto_goTypes,
		DependencyIndexes: file_plugin_pkg_services_networks_nebius_vpc_vpc_proto_depIdxs,
		MessageInfos:      file_plugin_pkg_services_networks_nebius_vpc_vpc_proto_msgTypes,
	}.Build()
	File_plugin_pkg_services_networks_nebius_vpc_vpc_proto = out.File
	file_plugin_pkg_services_networks_nebius_vpc_vpc_proto_goTypes = nil
	file_plugin_pkg_services_networks_nebius_vpc_vpc_proto_depIdxs = nil
}
