// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.5
// source: stretch/plugin/pkg/services/peerings/api/peerings.proto

package api

import (
	context "context"

	api "github.com/Azure/aks-flex/flex-plugin/api"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Peerings_CreateOrUpdate_FullMethodName = "/peerings.Peerings/CreateOrUpdate"
	Peerings_List_FullMethodName           = "/peerings.Peerings/List"
	Peerings_Get_FullMethodName            = "/peerings.Peerings/Get"
	Peerings_Delete_FullMethodName         = "/peerings.Peerings/Delete"
)

// PeeringsClient is the client API for Peerings service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PeeringsClient interface {
	CreateOrUpdate(ctx context.Context, in *api.CreateOrUpdateRequest, opts ...grpc.CallOption) (*api.CreateOrUpdateResponse, error)
	List(ctx context.Context, in *api.ListRequest, opts ...grpc.CallOption) (*api.ListResponse, error)
	Get(ctx context.Context, in *api.GetRequest, opts ...grpc.CallOption) (*api.GetResponse, error)
	Delete(ctx context.Context, in *api.DeleteRequest, opts ...grpc.CallOption) (*api.DeleteResponse, error)
}

type peeringsClient struct {
	cc grpc.ClientConnInterface
}

func NewPeeringsClient(cc grpc.ClientConnInterface) PeeringsClient {
	return &peeringsClient{cc}
}

func (c *peeringsClient) CreateOrUpdate(ctx context.Context, in *api.CreateOrUpdateRequest, opts ...grpc.CallOption) (*api.CreateOrUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(api.CreateOrUpdateResponse)
	err := c.cc.Invoke(ctx, Peerings_CreateOrUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peeringsClient) List(ctx context.Context, in *api.ListRequest, opts ...grpc.CallOption) (*api.ListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(api.ListResponse)
	err := c.cc.Invoke(ctx, Peerings_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peeringsClient) Get(ctx context.Context, in *api.GetRequest, opts ...grpc.CallOption) (*api.GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(api.GetResponse)
	err := c.cc.Invoke(ctx, Peerings_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peeringsClient) Delete(ctx context.Context, in *api.DeleteRequest, opts ...grpc.CallOption) (*api.DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(api.DeleteResponse)
	err := c.cc.Invoke(ctx, Peerings_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PeeringsServer is the server API for Peerings service.
// All implementations must embed UnimplementedPeeringsServer
// for forward compatibility.
type PeeringsServer interface {
	CreateOrUpdate(context.Context, *api.CreateOrUpdateRequest) (*api.CreateOrUpdateResponse, error)
	List(context.Context, *api.ListRequest) (*api.ListResponse, error)
	Get(context.Context, *api.GetRequest) (*api.GetResponse, error)
	Delete(context.Context, *api.DeleteRequest) (*api.DeleteResponse, error)
	mustEmbedUnimplementedPeeringsServer()
}

// UnimplementedPeeringsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPeeringsServer struct{}

func (UnimplementedPeeringsServer) CreateOrUpdate(context.Context, *api.CreateOrUpdateRequest) (*api.CreateOrUpdateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateOrUpdate not implemented")
}
func (UnimplementedPeeringsServer) List(context.Context, *api.ListRequest) (*api.ListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedPeeringsServer) Get(context.Context, *api.GetRequest) (*api.GetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedPeeringsServer) Delete(context.Context, *api.DeleteRequest) (*api.DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedPeeringsServer) mustEmbedUnimplementedPeeringsServer() {}
func (UnimplementedPeeringsServer) testEmbeddedByValue()                  {}

// UnsafePeeringsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PeeringsServer will
// result in compilation errors.
type UnsafePeeringsServer interface {
	mustEmbedUnimplementedPeeringsServer()
}

func RegisterPeeringsServer(s grpc.ServiceRegistrar, srv PeeringsServer) {
	// If the following call panics, it indicates UnimplementedPeeringsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Peerings_ServiceDesc, srv)
}

func _Peerings_CreateOrUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(api.CreateOrUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeeringsServer).CreateOrUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Peerings_CreateOrUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeeringsServer).CreateOrUpdate(ctx, req.(*api.CreateOrUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Peerings_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(api.ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeeringsServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Peerings_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeeringsServer).List(ctx, req.(*api.ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Peerings_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(api.GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeeringsServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Peerings_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeeringsServer).Get(ctx, req.(*api.GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Peerings_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(api.DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeeringsServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Peerings_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeeringsServer).Delete(ctx, req.(*api.DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Peerings_ServiceDesc is the grpc.ServiceDesc for Peerings service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Peerings_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "peerings.Peerings",
	HandlerType: (*PeeringsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrUpdate",
			Handler:    _Peerings_CreateOrUpdate_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Peerings_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Peerings_Get_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Peerings_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stretch/plugin/pkg/services/peerings/api/peerings.proto",
}
